//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}add-mode"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}admin"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}drop-mode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addMode",
    "admin",
    "dropMode"
})
@XmlRootElement(name = "adhoc_conference")
public class AdhocConference {

    @XmlElement(name = "add-mode", required = true)
    protected AddMode addMode;
    @XmlElement(required = true)
    protected String admin;
    @XmlElement(name = "drop-mode", required = true)
    protected DropMode dropMode;

    /**
     * Gets the value of the addMode property.
     * 
     * @return
     *     possible object is
     *     {@link AddMode }
     *     
     */
    public AddMode getAddMode() {
        return addMode;
    }

    /**
     * Sets the value of the addMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddMode }
     *     
     */
    public void setAddMode(AddMode value) {
        this.addMode = value;
    }

    /**
     * Gets the value of the admin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * Sets the value of the admin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmin(String value) {
        this.admin = value;
    }

    /**
     * Gets the value of the dropMode property.
     * 
     * @return
     *     possible object is
     *     {@link DropMode }
     *     
     */
    public DropMode getDropMode() {
        return dropMode;
    }

    /**
     * Sets the value of the dropMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropMode }
     *     
     */
    public void setDropMode(DropMode value) {
        this.dropMode = value;
    }

}
