//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}group_id"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}start_tag"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}stop_tag"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}type" minOccurs="0"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}cfw"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}timeout"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupId",
    "startTag",
    "stopTag",
    "type",
    "cfw",
    "timeout"
})
@XmlRootElement(name = "assign_item")
public class AssignItem {

    @XmlElement(name = "group_id", required = true)
    protected String groupId;
    @XmlElement(name = "start_tag", required = true)
    protected String startTag;
    @XmlElement(name = "stop_tag", required = true)
    protected String stopTag;
    protected String type;
    @XmlElement(required = true)
    protected String cfw;
    @XmlElement(required = true)
    protected String timeout;

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the startTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTag() {
        return startTag;
    }

    /**
     * Sets the value of the startTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTag(String value) {
        this.startTag = value;
    }

    /**
     * Gets the value of the stopTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopTag() {
        return stopTag;
    }

    /**
     * Sets the value of the stopTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopTag(String value) {
        this.stopTag = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the cfw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfw() {
        return cfw;
    }

    /**
     * Sets the value of the cfw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfw(String value) {
        this.cfw = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

}
