//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}blf-speed-dial_item" maxOccurs="unbounded"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}device"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blfSpeedDialItem",
    "device"
})
@XmlRootElement(name = "blf-speed-dial_list")
public class BlfSpeedDialList {

    @XmlElement(name = "blf-speed-dial_item", required = true)
    protected List<BlfSpeedDialItem> blfSpeedDialItem;
    @XmlElement(required = true)
    protected String device;

    /**
     * Gets the value of the blfSpeedDialItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blfSpeedDialItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlfSpeedDialItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlfSpeedDialItem }
     * 
     * 
     */
    public List<BlfSpeedDialItem> getBlfSpeedDialItem() {
        if (blfSpeedDialItem == null) {
            blfSpeedDialItem = new ArrayList<BlfSpeedDialItem>();
        }
        return this.blfSpeedDialItem;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevice(String value) {
        this.device = value;
    }

}
