//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}pattern_id"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}blocking_pattern"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}blocking_option"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patternId",
    "blockingPattern",
    "blockingOption"
})
@XmlRootElement(name = "block_item")
public class BlockItem {

    @XmlElement(name = "pattern_id", required = true)
    protected String patternId;
    @XmlElement(name = "blocking_pattern", required = true)
    protected String blockingPattern;
    @XmlElement(name = "blocking_option", required = true)
    protected String blockingOption;

    /**
     * Gets the value of the patternId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatternId() {
        return patternId;
    }

    /**
     * Sets the value of the patternId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatternId(String value) {
        this.patternId = value;
    }

    /**
     * Gets the value of the blockingPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockingPattern() {
        return blockingPattern;
    }

    /**
     * Sets the value of the blockingPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockingPattern(String value) {
        this.blockingPattern = value;
    }

    /**
     * Gets the value of the blockingOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockingOption() {
        return blockingOption;
    }

    /**
     * Sets the value of the blockingOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockingOption(String value) {
        this.blockingOption = value;
    }

}
