//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}em_service"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}directory_service"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}myphoneapp_service"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emService",
    "directoryService",
    "myphoneappService"
})
@XmlRootElement(name = "exclude-services")
public class ExcludeServices {

    @XmlElement(name = "em_service", required = true)
    protected String emService;
    @XmlElement(name = "directory_service", required = true)
    protected String directoryService;
    @XmlElement(name = "myphoneapp_service", required = true)
    protected String myphoneappService;

    /**
     * Gets the value of the emService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmService() {
        return emService;
    }

    /**
     * Sets the value of the emService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmService(String value) {
        this.emService = value;
    }

    /**
     * Gets the value of the directoryService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryService() {
        return directoryService;
    }

    /**
     * Sets the value of the directoryService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryService(String value) {
        this.directoryService = value;
    }

    /**
     * Gets the value of the myphoneappService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyphoneappService() {
        return myphoneappService;
    }

    /**
     * Sets the value of the myphoneappService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyphoneappService(String value) {
        this.myphoneappService = value;
    }

}
