//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}fastdial"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}fastdial_number"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}fastdial_name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fastdial",
    "fastdialNumber",
    "fastdialName"
})
@XmlRootElement(name = "fastdial_item")
public class FastdialItem {

    @XmlElement(required = true)
    protected String fastdial;
    @XmlElement(name = "fastdial_number", required = true)
    protected String fastdialNumber;
    @XmlElement(name = "fastdial_name", required = true)
    protected String fastdialName;

    /**
     * Gets the value of the fastdial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastdial() {
        return fastdial;
    }

    /**
     * Sets the value of the fastdial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastdial(String value) {
        this.fastdial = value;
    }

    /**
     * Gets the value of the fastdialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastdialNumber() {
        return fastdialNumber;
    }

    /**
     * Sets the value of the fastdialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastdialNumber(String value) {
        this.fastdialNumber = value;
    }

    /**
     * Gets the value of the fastdialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastdialName() {
        return fastdialName;
    }

    /**
     * Sets the value of the fastdialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastdialName(String value) {
        this.fastdialName = value;
    }

}
