//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}block_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}date_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}day_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}after-hours_login"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}override-code"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}pstn-prefix_list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blockList",
    "dateList",
    "dayList",
    "afterHoursLogin",
    "overrideCode",
    "pstnPrefixList"
})
@XmlRootElement(name = "global-after-hours")
public class GlobalAfterHours {

    @XmlElement(name = "block_list", required = true)
    protected BlockList blockList;
    @XmlElement(name = "date_list", required = true)
    protected DateList dateList;
    @XmlElement(name = "day_list", required = true)
    protected DayList dayList;
    @XmlElement(name = "after-hours_login", required = true)
    protected AfterHoursLogin afterHoursLogin;
    @XmlElement(name = "override-code", required = true)
    protected String overrideCode;
    @XmlElement(name = "pstn-prefix_list", required = true)
    protected PstnPrefixList pstnPrefixList;

    /**
     * Gets the value of the blockList property.
     * 
     * @return
     *     possible object is
     *     {@link BlockList }
     *     
     */
    public BlockList getBlockList() {
        return blockList;
    }

    /**
     * Sets the value of the blockList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockList }
     *     
     */
    public void setBlockList(BlockList value) {
        this.blockList = value;
    }

    /**
     * Gets the value of the dateList property.
     * 
     * @return
     *     possible object is
     *     {@link DateList }
     *     
     */
    public DateList getDateList() {
        return dateList;
    }

    /**
     * Sets the value of the dateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateList }
     *     
     */
    public void setDateList(DateList value) {
        this.dateList = value;
    }

    /**
     * Gets the value of the dayList property.
     * 
     * @return
     *     possible object is
     *     {@link DayList }
     *     
     */
    public DayList getDayList() {
        return dayList;
    }

    /**
     * Sets the value of the dayList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayList }
     *     
     */
    public void setDayList(DayList value) {
        this.dayList = value;
    }

    /**
     * Gets the value of the afterHoursLogin property.
     * 
     * @return
     *     possible object is
     *     {@link AfterHoursLogin }
     *     
     */
    public AfterHoursLogin getAfterHoursLogin() {
        return afterHoursLogin;
    }

    /**
     * Sets the value of the afterHoursLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfterHoursLogin }
     *     
     */
    public void setAfterHoursLogin(AfterHoursLogin value) {
        this.afterHoursLogin = value;
    }

    /**
     * Gets the value of the overrideCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideCode() {
        return overrideCode;
    }

    /**
     * Sets the value of the overrideCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideCode(String value) {
        this.overrideCode = value;
    }

    /**
     * Gets the value of the pstnPrefixList property.
     * 
     * @return
     *     possible object is
     *     {@link PstnPrefixList }
     *     
     */
    public PstnPrefixList getPstnPrefixList() {
        return pstnPrefixList;
    }

    /**
     * Sets the value of the pstnPrefixList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PstnPrefixList }
     *     
     */
    public void setPstnPrefixList(PstnPrefixList value) {
        this.pstnPrefixList = value;
    }

}
