//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDevTemplateID"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}after-hours"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}block-blind-xf-fallback"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}button-layout_phone_7931"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}button-layout_list"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}capf-ip-in-cnf"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}codec"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}adhoc_conference"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}fastdial_list"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}feature-button_list"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}url-button_list"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}features_blocked"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}keep-conference"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}keypad-normalize"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}keyphone"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}mlpp"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}mtp"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}multicast-moh"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}night-service_bell"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}privacy"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}privacy-button"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}phone_service"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}softkeys"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}transfer-park"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}transfer-pattern"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}busy-trigger-per-button"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}emergency-resp_location"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}max-calls-per-button"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}network_locale"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}nte-end-digit-delay"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}transfer_max-length"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}user_locale"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}keepalive"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}lpcor"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}exclude-services"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}park"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}paging-dn"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}speed-dial_list"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ssh"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}phone_type"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}url_services_list"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isDevTemplateID",
    "afterHours",
    "blockBlindXfFallback",
    "buttonLayoutPhone7931",
    "buttonLayoutList",
    "capfIpInCnf",
    "codec",
    "adhocConference",
    "fastdialList",
    "featureButtonList",
    "urlButtonList",
    "featuresBlocked",
    "keepConference",
    "keypadNormalize",
    "keyphone",
    "mlpp",
    "mtp",
    "multicastMoh",
    "nightServiceBell",
    "privacy",
    "privacyButton",
    "phoneService",
    "softkeys",
    "transferPark",
    "transferPattern",
    "busyTriggerPerButton",
    "emergencyRespLocation",
    "maxCallsPerButton",
    "networkLocale",
    "nteEndDigitDelay",
    "transferMaxLength",
    "userLocale",
    "keepalive",
    "lpcor",
    "excludeServices",
    "park",
    "pagingDn",
    "speedDialList",
    "ssh",
    "phoneType",
    "urlServicesList"
})
@XmlRootElement(name = "ISDeviceTemplate")
public class ISDeviceTemplate {

    @XmlElement(name = "ISDevTemplateID", required = true)
    protected String isDevTemplateID;
    @XmlElement(name = "after-hours")
    protected AfterHours afterHours;
    @XmlElement(name = "block-blind-xf-fallback")
    protected String blockBlindXfFallback;
    @XmlElement(name = "button-layout_phone_7931")
    protected String buttonLayoutPhone7931;
    @XmlElement(name = "button-layout_list")
    protected ButtonLayoutList buttonLayoutList;
    @XmlElement(name = "capf-ip-in-cnf")
    protected String capfIpInCnf;
    protected Codec codec;
    @XmlElement(name = "adhoc_conference")
    protected AdhocConference adhocConference;
    @XmlElement(name = "fastdial_list")
    protected FastdialList fastdialList;
    @XmlElement(name = "feature-button_list")
    protected FeatureButtonList featureButtonList;
    @XmlElement(name = "url-button_list")
    protected UrlButtonList urlButtonList;
    @XmlElement(name = "features_blocked")
    protected String featuresBlocked;
    @XmlElement(name = "keep-conference")
    protected KeepConference keepConference;
    @XmlElement(name = "keypad-normalize")
    protected String keypadNormalize;
    protected String keyphone;
    protected Mlpp mlpp;
    protected String mtp;
    @XmlElement(name = "multicast-moh")
    protected String multicastMoh;
    @XmlElement(name = "night-service_bell")
    protected String nightServiceBell;
    protected String privacy;
    @XmlElement(name = "privacy-button")
    protected String privacyButton;
    @XmlElement(name = "phone_service")
    protected PhoneService phoneService;
    protected Softkeys softkeys;
    @XmlElement(name = "transfer-park")
    protected TransferPark transferPark;
    @XmlElement(name = "transfer-pattern")
    protected TransferPattern transferPattern;
    @XmlElement(name = "busy-trigger-per-button")
    protected String busyTriggerPerButton;
    @XmlElement(name = "emergency-resp_location")
    protected String emergencyRespLocation;
    @XmlElement(name = "max-calls-per-button")
    protected String maxCallsPerButton;
    @XmlElement(name = "network_locale")
    protected String networkLocale;
    @XmlElement(name = "nte-end-digit-delay")
    protected String nteEndDigitDelay;
    @XmlElement(name = "transfer_max-length")
    protected String transferMaxLength;
    @XmlElement(name = "user_locale")
    protected String userLocale;
    protected Keepalive keepalive;
    protected Lpcor lpcor;
    @XmlElement(name = "exclude-services")
    protected ExcludeServices excludeServices;
    protected Park park;
    @XmlElement(name = "paging-dn")
    protected PagingDn pagingDn;
    @XmlElement(name = "speed-dial_list")
    protected SpeedDialList speedDialList;
    protected Ssh ssh;
    @XmlElement(name = "phone_type")
    protected PhoneType phoneType;
    @XmlElement(name = "url_services_list")
    protected UrlServicesList urlServicesList;

    /**
     * Gets the value of the isDevTemplateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDevTemplateID() {
        return isDevTemplateID;
    }

    /**
     * Sets the value of the isDevTemplateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDevTemplateID(String value) {
        this.isDevTemplateID = value;
    }

    /**
     * Gets the value of the afterHours property.
     * 
     * @return
     *     possible object is
     *     {@link AfterHours }
     *     
     */
    public AfterHours getAfterHours() {
        return afterHours;
    }

    /**
     * Sets the value of the afterHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfterHours }
     *     
     */
    public void setAfterHours(AfterHours value) {
        this.afterHours = value;
    }

    /**
     * Gets the value of the blockBlindXfFallback property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockBlindXfFallback() {
        return blockBlindXfFallback;
    }

    /**
     * Sets the value of the blockBlindXfFallback property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockBlindXfFallback(String value) {
        this.blockBlindXfFallback = value;
    }

    /**
     * Gets the value of the buttonLayoutPhone7931 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getButtonLayoutPhone7931() {
        return buttonLayoutPhone7931;
    }

    /**
     * Sets the value of the buttonLayoutPhone7931 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setButtonLayoutPhone7931(String value) {
        this.buttonLayoutPhone7931 = value;
    }

    /**
     * Gets the value of the buttonLayoutList property.
     * 
     * @return
     *     possible object is
     *     {@link ButtonLayoutList }
     *     
     */
    public ButtonLayoutList getButtonLayoutList() {
        return buttonLayoutList;
    }

    /**
     * Sets the value of the buttonLayoutList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ButtonLayoutList }
     *     
     */
    public void setButtonLayoutList(ButtonLayoutList value) {
        this.buttonLayoutList = value;
    }

    /**
     * Gets the value of the capfIpInCnf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapfIpInCnf() {
        return capfIpInCnf;
    }

    /**
     * Sets the value of the capfIpInCnf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapfIpInCnf(String value) {
        this.capfIpInCnf = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link Codec }
     *     
     */
    public Codec getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Codec }
     *     
     */
    public void setCodec(Codec value) {
        this.codec = value;
    }

    /**
     * Gets the value of the adhocConference property.
     * 
     * @return
     *     possible object is
     *     {@link AdhocConference }
     *     
     */
    public AdhocConference getAdhocConference() {
        return adhocConference;
    }

    /**
     * Sets the value of the adhocConference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdhocConference }
     *     
     */
    public void setAdhocConference(AdhocConference value) {
        this.adhocConference = value;
    }

    /**
     * Gets the value of the fastdialList property.
     * 
     * @return
     *     possible object is
     *     {@link FastdialList }
     *     
     */
    public FastdialList getFastdialList() {
        return fastdialList;
    }

    /**
     * Sets the value of the fastdialList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FastdialList }
     *     
     */
    public void setFastdialList(FastdialList value) {
        this.fastdialList = value;
    }

    /**
     * Gets the value of the featureButtonList property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureButtonList }
     *     
     */
    public FeatureButtonList getFeatureButtonList() {
        return featureButtonList;
    }

    /**
     * Sets the value of the featureButtonList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureButtonList }
     *     
     */
    public void setFeatureButtonList(FeatureButtonList value) {
        this.featureButtonList = value;
    }

    /**
     * Gets the value of the urlButtonList property.
     * 
     * @return
     *     possible object is
     *     {@link UrlButtonList }
     *     
     */
    public UrlButtonList getUrlButtonList() {
        return urlButtonList;
    }

    /**
     * Sets the value of the urlButtonList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlButtonList }
     *     
     */
    public void setUrlButtonList(UrlButtonList value) {
        this.urlButtonList = value;
    }

    /**
     * Gets the value of the featuresBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturesBlocked() {
        return featuresBlocked;
    }

    /**
     * Sets the value of the featuresBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturesBlocked(String value) {
        this.featuresBlocked = value;
    }

    /**
     * Gets the value of the keepConference property.
     * 
     * @return
     *     possible object is
     *     {@link KeepConference }
     *     
     */
    public KeepConference getKeepConference() {
        return keepConference;
    }

    /**
     * Sets the value of the keepConference property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeepConference }
     *     
     */
    public void setKeepConference(KeepConference value) {
        this.keepConference = value;
    }

    /**
     * Gets the value of the keypadNormalize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeypadNormalize() {
        return keypadNormalize;
    }

    /**
     * Sets the value of the keypadNormalize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeypadNormalize(String value) {
        this.keypadNormalize = value;
    }

    /**
     * Gets the value of the keyphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyphone() {
        return keyphone;
    }

    /**
     * Sets the value of the keyphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyphone(String value) {
        this.keyphone = value;
    }

    /**
     * Gets the value of the mlpp property.
     * 
     * @return
     *     possible object is
     *     {@link Mlpp }
     *     
     */
    public Mlpp getMlpp() {
        return mlpp;
    }

    /**
     * Sets the value of the mlpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mlpp }
     *     
     */
    public void setMlpp(Mlpp value) {
        this.mlpp = value;
    }

    /**
     * Gets the value of the mtp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtp() {
        return mtp;
    }

    /**
     * Sets the value of the mtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtp(String value) {
        this.mtp = value;
    }

    /**
     * Gets the value of the multicastMoh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMulticastMoh() {
        return multicastMoh;
    }

    /**
     * Sets the value of the multicastMoh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMulticastMoh(String value) {
        this.multicastMoh = value;
    }

    /**
     * Gets the value of the nightServiceBell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNightServiceBell() {
        return nightServiceBell;
    }

    /**
     * Sets the value of the nightServiceBell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNightServiceBell(String value) {
        this.nightServiceBell = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacy(String value) {
        this.privacy = value;
    }

    /**
     * Gets the value of the privacyButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyButton() {
        return privacyButton;
    }

    /**
     * Sets the value of the privacyButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyButton(String value) {
        this.privacyButton = value;
    }

    /**
     * Gets the value of the phoneService property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneService }
     *     
     */
    public PhoneService getPhoneService() {
        return phoneService;
    }

    /**
     * Sets the value of the phoneService property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneService }
     *     
     */
    public void setPhoneService(PhoneService value) {
        this.phoneService = value;
    }

    /**
     * Gets the value of the softkeys property.
     * 
     * @return
     *     possible object is
     *     {@link Softkeys }
     *     
     */
    public Softkeys getSoftkeys() {
        return softkeys;
    }

    /**
     * Sets the value of the softkeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Softkeys }
     *     
     */
    public void setSoftkeys(Softkeys value) {
        this.softkeys = value;
    }

    /**
     * Gets the value of the transferPark property.
     * 
     * @return
     *     possible object is
     *     {@link TransferPark }
     *     
     */
    public TransferPark getTransferPark() {
        return transferPark;
    }

    /**
     * Sets the value of the transferPark property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferPark }
     *     
     */
    public void setTransferPark(TransferPark value) {
        this.transferPark = value;
    }

    /**
     * Gets the value of the transferPattern property.
     * 
     * @return
     *     possible object is
     *     {@link TransferPattern }
     *     
     */
    public TransferPattern getTransferPattern() {
        return transferPattern;
    }

    /**
     * Sets the value of the transferPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferPattern }
     *     
     */
    public void setTransferPattern(TransferPattern value) {
        this.transferPattern = value;
    }

    /**
     * Gets the value of the busyTriggerPerButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusyTriggerPerButton() {
        return busyTriggerPerButton;
    }

    /**
     * Sets the value of the busyTriggerPerButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusyTriggerPerButton(String value) {
        this.busyTriggerPerButton = value;
    }

    /**
     * Gets the value of the emergencyRespLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergencyRespLocation() {
        return emergencyRespLocation;
    }

    /**
     * Sets the value of the emergencyRespLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergencyRespLocation(String value) {
        this.emergencyRespLocation = value;
    }

    /**
     * Gets the value of the maxCallsPerButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxCallsPerButton() {
        return maxCallsPerButton;
    }

    /**
     * Sets the value of the maxCallsPerButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxCallsPerButton(String value) {
        this.maxCallsPerButton = value;
    }

    /**
     * Gets the value of the networkLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkLocale() {
        return networkLocale;
    }

    /**
     * Sets the value of the networkLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkLocale(String value) {
        this.networkLocale = value;
    }

    /**
     * Gets the value of the nteEndDigitDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNteEndDigitDelay() {
        return nteEndDigitDelay;
    }

    /**
     * Sets the value of the nteEndDigitDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNteEndDigitDelay(String value) {
        this.nteEndDigitDelay = value;
    }

    /**
     * Gets the value of the transferMaxLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferMaxLength() {
        return transferMaxLength;
    }

    /**
     * Sets the value of the transferMaxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferMaxLength(String value) {
        this.transferMaxLength = value;
    }

    /**
     * Gets the value of the userLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLocale() {
        return userLocale;
    }

    /**
     * Sets the value of the userLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLocale(String value) {
        this.userLocale = value;
    }

    /**
     * Gets the value of the keepalive property.
     * 
     * @return
     *     possible object is
     *     {@link Keepalive }
     *     
     */
    public Keepalive getKeepalive() {
        return keepalive;
    }

    /**
     * Sets the value of the keepalive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keepalive }
     *     
     */
    public void setKeepalive(Keepalive value) {
        this.keepalive = value;
    }

    /**
     * Gets the value of the lpcor property.
     * 
     * @return
     *     possible object is
     *     {@link Lpcor }
     *     
     */
    public Lpcor getLpcor() {
        return lpcor;
    }

    /**
     * Sets the value of the lpcor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lpcor }
     *     
     */
    public void setLpcor(Lpcor value) {
        this.lpcor = value;
    }

    /**
     * Gets the value of the excludeServices property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludeServices }
     *     
     */
    public ExcludeServices getExcludeServices() {
        return excludeServices;
    }

    /**
     * Sets the value of the excludeServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludeServices }
     *     
     */
    public void setExcludeServices(ExcludeServices value) {
        this.excludeServices = value;
    }

    /**
     * Gets the value of the park property.
     * 
     * @return
     *     possible object is
     *     {@link Park }
     *     
     */
    public Park getPark() {
        return park;
    }

    /**
     * Sets the value of the park property.
     * 
     * @param value
     *     allowed object is
     *     {@link Park }
     *     
     */
    public void setPark(Park value) {
        this.park = value;
    }

    /**
     * Gets the value of the pagingDn property.
     * 
     * @return
     *     possible object is
     *     {@link PagingDn }
     *     
     */
    public PagingDn getPagingDn() {
        return pagingDn;
    }

    /**
     * Sets the value of the pagingDn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagingDn }
     *     
     */
    public void setPagingDn(PagingDn value) {
        this.pagingDn = value;
    }

    /**
     * Gets the value of the speedDialList property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedDialList }
     *     
     */
    public SpeedDialList getSpeedDialList() {
        return speedDialList;
    }

    /**
     * Sets the value of the speedDialList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedDialList }
     *     
     */
    public void setSpeedDialList(SpeedDialList value) {
        this.speedDialList = value;
    }

    /**
     * Gets the value of the ssh property.
     * 
     * @return
     *     possible object is
     *     {@link Ssh }
     *     
     */
    public Ssh getSsh() {
        return ssh;
    }

    /**
     * Sets the value of the ssh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ssh }
     *     
     */
    public void setSsh(Ssh value) {
        this.ssh = value;
    }

    /**
     * Gets the value of the phoneType property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneType }
     *     
     */
    public PhoneType getPhoneType() {
        return phoneType;
    }

    /**
     * Sets the value of the phoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneType }
     *     
     */
    public void setPhoneType(PhoneType value) {
        this.phoneType = value;
    }

    /**
     * Gets the value of the urlServicesList property.
     * 
     * @return
     *     possible object is
     *     {@link UrlServicesList }
     *     
     */
    public UrlServicesList getUrlServicesList() {
        return urlServicesList;
    }

    /**
     * Sets the value of the urlServicesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlServicesList }
     *     
     */
    public void setUrlServicesList(UrlServicesList value) {
        this.urlServicesList = value;
    }

}
