//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDirectoryTag"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDirectoryNumber"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}firstName"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}lastName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isDirectoryTag",
    "isDirectoryNumber",
    "firstName",
    "lastName"
})
@XmlRootElement(name = "ISDirectoryEntry")
public class ISDirectoryEntry {

    @XmlElement(name = "ISDirectoryTag", required = true)
    protected String isDirectoryTag;
    @XmlElement(name = "ISDirectoryNumber", required = true)
    protected String isDirectoryNumber;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String lastName;

    /**
     * Gets the value of the isDirectoryTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDirectoryTag() {
        return isDirectoryTag;
    }

    /**
     * Sets the value of the isDirectoryTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDirectoryTag(String value) {
        this.isDirectoryTag = value;
    }

    /**
     * Gets the value of the isDirectoryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDirectoryNumber() {
        return isDirectoryNumber;
    }

    /**
     * Sets the value of the isDirectoryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDirectoryNumber(String value) {
        this.isDirectoryNumber = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

}
