//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISexecCLIResponse"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISexecCLIError"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iSexecCLIResponse",
    "iSexecCLIError"
})
@XmlRootElement(name = "ISexecCLIResult")
public class ISexecCLIResult {

    @XmlElement(name = "ISexecCLIResponse", required = true)
    protected String iSexecCLIResponse;
    @XmlElement(name = "ISexecCLIError", required = true)
    protected String iSexecCLIError;

    /**
     * Gets the value of the iSexecCLIResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISexecCLIResponse() {
        return iSexecCLIResponse;
    }

    /**
     * Sets the value of the iSexecCLIResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISexecCLIResponse(String value) {
        this.iSexecCLIResponse = value;
    }

    /**
     * Gets the value of the iSexecCLIError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISexecCLIError() {
        return iSexecCLIError;
    }

    /**
     * Sets the value of the iSexecCLIError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISexecCLIError(String value) {
        this.iSexecCLIError = value;
    }

}
