//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISExtTemplateID"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}allow"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}call-forward"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}call-waiting"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}caller-id_blocked"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}corlist"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}cti"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}description"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}hold-alert"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}huntstop"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}moh-group"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}mwi"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}mwi-type"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}pickup-group"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}transfer-recall_timeout"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}translate"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}translation-profile"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isExtTemplateID",
    "allow",
    "callForward",
    "callWaiting",
    "callerIdBlocked",
    "corlist",
    "cti",
    "description",
    "holdAlert",
    "huntstop",
    "mohGroup",
    "mwi",
    "mwiType",
    "pickupGroup",
    "transferRecallTimeout",
    "translate",
    "translationProfile"
})
@XmlRootElement(name = "ISExtensionTemplate")
public class ISExtensionTemplate {

    @XmlElement(name = "ISExtTemplateID", required = true)
    protected String isExtTemplateID;
    protected Allow allow;
    @XmlElement(name = "call-forward")
    protected CallForward callForward;
    @XmlElement(name = "call-waiting")
    protected CallWaiting callWaiting;
    @XmlElement(name = "caller-id_blocked")
    protected String callerIdBlocked;
    protected Corlist corlist;
    protected Cti cti;
    protected String description;
    @XmlElement(name = "hold-alert")
    protected HoldAlert holdAlert;
    protected Huntstop huntstop;
    @XmlElement(name = "moh-group")
    protected String mohGroup;
    protected Mwi mwi;
    @XmlElement(name = "mwi-type")
    protected String mwiType;
    @XmlElement(name = "pickup-group")
    protected String pickupGroup;
    @XmlElement(name = "transfer-recall_timeout")
    protected String transferRecallTimeout;
    protected Translate translate;
    @XmlElement(name = "translation-profile")
    protected TranslationProfile translationProfile;

    /**
     * Gets the value of the isExtTemplateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISExtTemplateID() {
        return isExtTemplateID;
    }

    /**
     * Sets the value of the isExtTemplateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISExtTemplateID(String value) {
        this.isExtTemplateID = value;
    }

    /**
     * Gets the value of the allow property.
     * 
     * @return
     *     possible object is
     *     {@link Allow }
     *     
     */
    public Allow getAllow() {
        return allow;
    }

    /**
     * Sets the value of the allow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Allow }
     *     
     */
    public void setAllow(Allow value) {
        this.allow = value;
    }

    /**
     * Gets the value of the callForward property.
     * 
     * @return
     *     possible object is
     *     {@link CallForward }
     *     
     */
    public CallForward getCallForward() {
        return callForward;
    }

    /**
     * Sets the value of the callForward property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallForward }
     *     
     */
    public void setCallForward(CallForward value) {
        this.callForward = value;
    }

    /**
     * Gets the value of the callWaiting property.
     * 
     * @return
     *     possible object is
     *     {@link CallWaiting }
     *     
     */
    public CallWaiting getCallWaiting() {
        return callWaiting;
    }

    /**
     * Sets the value of the callWaiting property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallWaiting }
     *     
     */
    public void setCallWaiting(CallWaiting value) {
        this.callWaiting = value;
    }

    /**
     * Gets the value of the callerIdBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerIdBlocked() {
        return callerIdBlocked;
    }

    /**
     * Sets the value of the callerIdBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerIdBlocked(String value) {
        this.callerIdBlocked = value;
    }

    /**
     * Gets the value of the corlist property.
     * 
     * @return
     *     possible object is
     *     {@link Corlist }
     *     
     */
    public Corlist getCorlist() {
        return corlist;
    }

    /**
     * Sets the value of the corlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Corlist }
     *     
     */
    public void setCorlist(Corlist value) {
        this.corlist = value;
    }

    /**
     * Gets the value of the cti property.
     * 
     * @return
     *     possible object is
     *     {@link Cti }
     *     
     */
    public Cti getCti() {
        return cti;
    }

    /**
     * Sets the value of the cti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cti }
     *     
     */
    public void setCti(Cti value) {
        this.cti = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the holdAlert property.
     * 
     * @return
     *     possible object is
     *     {@link HoldAlert }
     *     
     */
    public HoldAlert getHoldAlert() {
        return holdAlert;
    }

    /**
     * Sets the value of the holdAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldAlert }
     *     
     */
    public void setHoldAlert(HoldAlert value) {
        this.holdAlert = value;
    }

    /**
     * Gets the value of the huntstop property.
     * 
     * @return
     *     possible object is
     *     {@link Huntstop }
     *     
     */
    public Huntstop getHuntstop() {
        return huntstop;
    }

    /**
     * Sets the value of the huntstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Huntstop }
     *     
     */
    public void setHuntstop(Huntstop value) {
        this.huntstop = value;
    }

    /**
     * Gets the value of the mohGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMohGroup() {
        return mohGroup;
    }

    /**
     * Sets the value of the mohGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMohGroup(String value) {
        this.mohGroup = value;
    }

    /**
     * Gets the value of the mwi property.
     * 
     * @return
     *     possible object is
     *     {@link Mwi }
     *     
     */
    public Mwi getMwi() {
        return mwi;
    }

    /**
     * Sets the value of the mwi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mwi }
     *     
     */
    public void setMwi(Mwi value) {
        this.mwi = value;
    }

    /**
     * Gets the value of the mwiType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMwiType() {
        return mwiType;
    }

    /**
     * Sets the value of the mwiType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMwiType(String value) {
        this.mwiType = value;
    }

    /**
     * Gets the value of the pickupGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupGroup() {
        return pickupGroup;
    }

    /**
     * Sets the value of the pickupGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupGroup(String value) {
        this.pickupGroup = value;
    }

    /**
     * Gets the value of the transferRecallTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferRecallTimeout() {
        return transferRecallTimeout;
    }

    /**
     * Sets the value of the transferRecallTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferRecallTimeout(String value) {
        this.transferRecallTimeout = value;
    }

    /**
     * Gets the value of the translate property.
     * 
     * @return
     *     possible object is
     *     {@link Translate }
     *     
     */
    public Translate getTranslate() {
        return translate;
    }

    /**
     * Sets the value of the translate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Translate }
     *     
     */
    public void setTranslate(Translate value) {
        this.translate = value;
    }

    /**
     * Gets the value of the translationProfile property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationProfile }
     *     
     */
    public TranslationProfile getTranslationProfile() {
        return translationProfile;
    }

    /**
     * Sets the value of the translationProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationProfile }
     *     
     */
    public void setTranslationProfile(TranslationProfile value) {
        this.translationProfile = value;
    }

}
