//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISExtTemplateID"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISKeyword"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isExtTemplateID",
    "isKeyword"
})
@XmlRootElement(name = "ISgetExtensionTemplate")
public class ISgetExtensionTemplate {

    @XmlElement(name = "ISExtTemplateID")
    protected String isExtTemplateID;
    @XmlElement(name = "ISKeyword")
    protected String isKeyword;

    /**
     * Gets the value of the isExtTemplateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISExtTemplateID() {
        return isExtTemplateID;
    }

    /**
     * Sets the value of the isExtTemplateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISExtTemplateID(String value) {
        this.isExtTemplateID = value;
    }

    /**
     * Gets the value of the isKeyword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISKeyword() {
        return isKeyword;
    }

    /**
     * Sets the value of the isKeyword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISKeyword(String value) {
        this.isKeyword = value;
    }

}
