//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISAddress"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMode"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISVersion"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDeviceRegistered"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPeakDeviceRegistered"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPeakDeviceRegisteredTime"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISKeepAliveInterval"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISConfiguredDevice"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISConfiguredExtension"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISServiceEngine"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISName"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPortNumber"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMaxConference"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMaxRedirect"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMaxEphone"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMaxDN"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISVoiceMail"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISUrlServices"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}global-after-hours"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}application_name"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}auth_credential_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}auto"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}auto-reg-ephone"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}bulk-speed-dial_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}prefix"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}global-call-forward"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}call-park"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}caller-id"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}calling-number"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}cnf-file"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}default_codec"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}conference"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}date-format"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}device-security-mode"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}dialplan-pattern_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}directory"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}dn-webedit"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}em"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ephone-reg"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}extension-assigner"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}fac"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}fxo"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}hunt-group"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}internal-call"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ip"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}keepalive"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}live-record"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}load_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}load-cfg-file_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}log"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}login"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}max-conferences"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}max-dn"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}max-ephones"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}max-redirect"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}modem"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}moh_file"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}moh-file-buffer"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}multicast"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}mwi-server"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}network-locale_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}night-service"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}pin"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}pin_override"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}privacy"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}privacy-on-hold"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}protocol"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}sdspfarm"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}secondary-dialtone"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}secure-signaling"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}server-security-mode"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}service"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ssh"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}standby"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}system_message"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}tftp-server-credentials"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}time-format"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}time-webedit"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}time-zone"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}timeouts"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}transfer-digit-collect"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}transfer-pattern_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}transfer-system"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}trunk_optimization_pre_connect"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}url_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}user-locale_list"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}video"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}voicemail"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}web"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}xml"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isAddress",
    "isMode",
    "isVersion",
    "isDeviceRegistered",
    "isPeakDeviceRegistered",
    "isPeakDeviceRegisteredTime",
    "isKeepAliveInterval",
    "isConfiguredDevice",
    "isConfiguredExtension",
    "isServiceEngine",
    "isName",
    "isPortNumber",
    "isMaxConference",
    "isMaxRedirect",
    "isMaxEphone",
    "isMaxDN",
    "isVoiceMail",
    "isUrlServices",
    "globalAfterHours",
    "applicationName",
    "authCredentialList",
    "auto",
    "autoRegEphone",
    "bulkSpeedDialList",
    "prefix",
    "globalCallForward",
    "callPark",
    "callerId",
    "callingNumber",
    "cnfFile",
    "defaultCodec",
    "conference",
    "dateFormat",
    "deviceSecurityMode",
    "dialplanPatternList",
    "directory",
    "dnWebedit",
    "em",
    "ephoneReg",
    "extensionAssigner",
    "fac",
    "fxo",
    "huntGroup",
    "internalCall",
    "ip",
    "keepalive",
    "liveRecord",
    "loadList",
    "loadCfgFileList",
    "log",
    "login",
    "maxConferences",
    "maxDn",
    "maxEphones",
    "maxRedirect",
    "modem",
    "mohFile",
    "mohFileBuffer",
    "multicast",
    "mwiServer",
    "networkLocaleList",
    "nightService",
    "pin",
    "pinOverride",
    "privacy",
    "privacyOnHold",
    "protocol",
    "sdspfarm",
    "secondaryDialtone",
    "secureSignaling",
    "serverSecurityMode",
    "service",
    "ssh",
    "standby",
    "systemMessage",
    "tftpServerCredentials",
    "timeFormat",
    "timeWebedit",
    "timeZone",
    "timeouts",
    "transferDigitCollect",
    "transferPatternList",
    "transferSystem",
    "trunkOptimizationPreConnect",
    "urlList",
    "userLocaleList",
    "video",
    "voicemail",
    "web",
    "xml"
})
@XmlRootElement(name = "ISGlobal")
public class ISGlobal {

    @XmlElement(name = "ISAddress", required = true)
    protected String isAddress;
    @XmlElement(name = "ISMode", required = true)
    protected String isMode;
    @XmlElement(name = "ISVersion", required = true)
    protected String isVersion;
    @XmlElement(name = "ISDeviceRegistered", required = true)
    protected String isDeviceRegistered;
    @XmlElement(name = "ISPeakDeviceRegistered", required = true)
    protected String isPeakDeviceRegistered;
    @XmlElement(name = "ISPeakDeviceRegisteredTime", required = true)
    protected String isPeakDeviceRegisteredTime;
    @XmlElement(name = "ISKeepAliveInterval", required = true)
    protected String isKeepAliveInterval;
    @XmlElement(name = "ISConfiguredDevice", required = true)
    protected String isConfiguredDevice;
    @XmlElement(name = "ISConfiguredExtension", required = true)
    protected String isConfiguredExtension;
    @XmlElement(name = "ISServiceEngine", required = true)
    protected String isServiceEngine;
    @XmlElement(name = "ISName", required = true)
    protected String isName;
    @XmlElement(name = "ISPortNumber", required = true)
    protected String isPortNumber;
    @XmlElement(name = "ISMaxConference", required = true)
    protected String isMaxConference;
    @XmlElement(name = "ISMaxRedirect", required = true)
    protected String isMaxRedirect;
    @XmlElement(name = "ISMaxEphone", required = true)
    protected String isMaxEphone;
    @XmlElement(name = "ISMaxDN", required = true)
    protected String isMaxDN;
    @XmlElement(name = "ISVoiceMail", required = true)
    protected String isVoiceMail;
    @XmlElement(name = "ISUrlServices", required = true)
    protected ISUrlServices isUrlServices;
    @XmlElement(name = "global-after-hours", required = true)
    protected GlobalAfterHours globalAfterHours;
    @XmlElement(name = "application_name", required = true)
    protected String applicationName;
    @XmlElement(name = "auth_credential_list", required = true)
    protected AuthCredentialList authCredentialList;
    @XmlElement(required = true)
    protected Auto auto;
    @XmlElement(name = "auto-reg-ephone", required = true)
    protected String autoRegEphone;
    @XmlElement(name = "bulk-speed-dial_list", required = true)
    protected BulkSpeedDialList bulkSpeedDialList;
    @XmlElement(required = true)
    protected String prefix;
    @XmlElement(name = "global-call-forward", required = true)
    protected GlobalCallForward globalCallForward;
    @XmlElement(name = "call-park", required = true)
    protected CallPark callPark;
    @XmlElement(name = "caller-id", required = true)
    protected CallerId callerId;
    @XmlElement(name = "calling-number", required = true)
    protected CallingNumber callingNumber;
    @XmlElement(name = "cnf-file", required = true)
    protected CnfFile cnfFile;
    @XmlElement(name = "default_codec", required = true)
    protected String defaultCodec;
    @XmlElement(required = true)
    protected Conference conference;
    @XmlElement(name = "date-format", required = true)
    protected String dateFormat;
    @XmlElement(name = "device-security-mode", required = true)
    protected String deviceSecurityMode;
    @XmlElement(name = "dialplan-pattern_list", required = true)
    protected DialplanPatternList dialplanPatternList;
    @XmlElement(required = true)
    protected Directory directory;
    @XmlElement(name = "dn-webedit", required = true)
    protected String dnWebedit;
    @XmlElement(required = true)
    protected Em em;
    @XmlElement(name = "ephone-reg", required = true)
    protected String ephoneReg;
    @XmlElement(name = "extension-assigner", required = true)
    protected ExtensionAssigner extensionAssigner;
    @XmlElement(required = true)
    protected Fac fac;
    @XmlElement(required = true)
    protected Fxo fxo;
    @XmlElement(name = "hunt-group", required = true)
    protected HuntGroup huntGroup;
    @XmlElement(name = "internal-call", required = true)
    protected InternalCall internalCall;
    @XmlElement(required = true)
    protected Ip ip;
    @XmlElement(required = true)
    protected Keepalive keepalive;
    @XmlElement(name = "live-record", required = true)
    protected String liveRecord;
    @XmlElement(name = "load_list", required = true)
    protected LoadList loadList;
    @XmlElement(name = "load-cfg-file_list", required = true)
    protected LoadCfgFileList loadCfgFileList;
    @XmlElement(required = true)
    protected Log log;
    @XmlElement(required = true)
    protected Login login;
    @XmlElement(name = "max-conferences", required = true)
    protected MaxConferences maxConferences;
    @XmlElement(name = "max-dn", required = true)
    protected MaxDn maxDn;
    @XmlElement(name = "max-ephones", required = true)
    protected String maxEphones;
    @XmlElement(name = "max-redirect", required = true)
    protected String maxRedirect;
    @XmlElement(required = true)
    protected Modem modem;
    @XmlElement(name = "moh_file", required = true)
    protected String mohFile;
    @XmlElement(name = "moh-file-buffer", required = true)
    protected String mohFileBuffer;
    @XmlElement(required = true)
    protected Multicast multicast;
    @XmlElement(name = "mwi-server", required = true)
    protected MwiServer mwiServer;
    @XmlElement(name = "network-locale_list", required = true)
    protected NetworkLocaleList networkLocaleList;
    @XmlElement(name = "night-service", required = true)
    protected NightService nightService;
    @XmlElement(required = true)
    protected String pin;
    @XmlElement(name = "pin_override", required = true)
    protected String pinOverride;
    @XmlElement(required = true)
    protected String privacy;
    @XmlElement(name = "privacy-on-hold", required = true)
    protected String privacyOnHold;
    @XmlElement(required = true)
    protected Protocol protocol;
    @XmlElement(required = true)
    protected Sdspfarm sdspfarm;
    @XmlElement(name = "secondary-dialtone", required = true)
    protected String secondaryDialtone;
    @XmlElement(name = "secure-signaling", required = true)
    protected SecureSignaling secureSignaling;
    @XmlElement(name = "server-security-mode", required = true)
    protected ServerSecurityMode serverSecurityMode;
    @XmlElement(required = true)
    protected Service service;
    @XmlElement(required = true)
    protected Ssh ssh;
    @XmlElement(required = true)
    protected Standby standby;
    @XmlElement(name = "system_message", required = true)
    protected String systemMessage;
    @XmlElement(name = "tftp-server-credentials", required = true)
    protected TftpServerCredentials tftpServerCredentials;
    @XmlElement(name = "time-format", required = true)
    protected String timeFormat;
    @XmlElement(name = "time-webedit", required = true)
    protected String timeWebedit;
    @XmlElement(name = "time-zone", required = true)
    protected String timeZone;
    @XmlElement(required = true)
    protected Timeouts timeouts;
    @XmlElement(name = "transfer-digit-collect", required = true)
    protected String transferDigitCollect;
    @XmlElement(name = "transfer-pattern_list", required = true)
    protected TransferPatternList transferPatternList;
    @XmlElement(name = "transfer-system", required = true)
    protected TransferSystem transferSystem;
    @XmlElement(name = "trunk_optimization_pre_connect", required = true)
    protected String trunkOptimizationPreConnect;
    @XmlElement(name = "url_list", required = true)
    protected UrlList urlList;
    @XmlElement(name = "user-locale_list", required = true)
    protected UserLocaleList userLocaleList;
    @XmlElement(required = true)
    protected Video video;
    @XmlElement(required = true)
    protected String voicemail;
    @XmlElement(required = true)
    protected Web web;
    @XmlElement(required = true)
    protected Xml xml;

    /**
     * Gets the value of the isAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISAddress() {
        return isAddress;
    }

    /**
     * Sets the value of the isAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISAddress(String value) {
        this.isAddress = value;
    }

    /**
     * Gets the value of the isMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMode() {
        return isMode;
    }

    /**
     * Sets the value of the isMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMode(String value) {
        this.isMode = value;
    }

    /**
     * Gets the value of the isVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVersion() {
        return isVersion;
    }

    /**
     * Sets the value of the isVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVersion(String value) {
        this.isVersion = value;
    }

    /**
     * Gets the value of the isDeviceRegistered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDeviceRegistered() {
        return isDeviceRegistered;
    }

    /**
     * Sets the value of the isDeviceRegistered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDeviceRegistered(String value) {
        this.isDeviceRegistered = value;
    }

    /**
     * Gets the value of the isPeakDeviceRegistered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPeakDeviceRegistered() {
        return isPeakDeviceRegistered;
    }

    /**
     * Sets the value of the isPeakDeviceRegistered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPeakDeviceRegistered(String value) {
        this.isPeakDeviceRegistered = value;
    }

    /**
     * Gets the value of the isPeakDeviceRegisteredTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPeakDeviceRegisteredTime() {
        return isPeakDeviceRegisteredTime;
    }

    /**
     * Sets the value of the isPeakDeviceRegisteredTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPeakDeviceRegisteredTime(String value) {
        this.isPeakDeviceRegisteredTime = value;
    }

    /**
     * Gets the value of the isKeepAliveInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISKeepAliveInterval() {
        return isKeepAliveInterval;
    }

    /**
     * Sets the value of the isKeepAliveInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISKeepAliveInterval(String value) {
        this.isKeepAliveInterval = value;
    }

    /**
     * Gets the value of the isConfiguredDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISConfiguredDevice() {
        return isConfiguredDevice;
    }

    /**
     * Sets the value of the isConfiguredDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISConfiguredDevice(String value) {
        this.isConfiguredDevice = value;
    }

    /**
     * Gets the value of the isConfiguredExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISConfiguredExtension() {
        return isConfiguredExtension;
    }

    /**
     * Sets the value of the isConfiguredExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISConfiguredExtension(String value) {
        this.isConfiguredExtension = value;
    }

    /**
     * Gets the value of the isServiceEngine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISServiceEngine() {
        return isServiceEngine;
    }

    /**
     * Sets the value of the isServiceEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISServiceEngine(String value) {
        this.isServiceEngine = value;
    }

    /**
     * Gets the value of the isName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISName() {
        return isName;
    }

    /**
     * Sets the value of the isName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISName(String value) {
        this.isName = value;
    }

    /**
     * Gets the value of the isPortNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPortNumber() {
        return isPortNumber;
    }

    /**
     * Sets the value of the isPortNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPortNumber(String value) {
        this.isPortNumber = value;
    }

    /**
     * Gets the value of the isMaxConference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMaxConference() {
        return isMaxConference;
    }

    /**
     * Sets the value of the isMaxConference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMaxConference(String value) {
        this.isMaxConference = value;
    }

    /**
     * Gets the value of the isMaxRedirect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMaxRedirect() {
        return isMaxRedirect;
    }

    /**
     * Sets the value of the isMaxRedirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMaxRedirect(String value) {
        this.isMaxRedirect = value;
    }

    /**
     * Gets the value of the isMaxEphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMaxEphone() {
        return isMaxEphone;
    }

    /**
     * Sets the value of the isMaxEphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMaxEphone(String value) {
        this.isMaxEphone = value;
    }

    /**
     * Gets the value of the isMaxDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMaxDN() {
        return isMaxDN;
    }

    /**
     * Sets the value of the isMaxDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMaxDN(String value) {
        this.isMaxDN = value;
    }

    /**
     * Gets the value of the isVoiceMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceMail() {
        return isVoiceMail;
    }

    /**
     * Sets the value of the isVoiceMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceMail(String value) {
        this.isVoiceMail = value;
    }

    /**
     * Gets the value of the isUrlServices property.
     * 
     * @return
     *     possible object is
     *     {@link ISUrlServices }
     *     
     */
    public ISUrlServices getISUrlServices() {
        return isUrlServices;
    }

    /**
     * Sets the value of the isUrlServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISUrlServices }
     *     
     */
    public void setISUrlServices(ISUrlServices value) {
        this.isUrlServices = value;
    }

    /**
     * Gets the value of the globalAfterHours property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalAfterHours }
     *     
     */
    public GlobalAfterHours getGlobalAfterHours() {
        return globalAfterHours;
    }

    /**
     * Sets the value of the globalAfterHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalAfterHours }
     *     
     */
    public void setGlobalAfterHours(GlobalAfterHours value) {
        this.globalAfterHours = value;
    }

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the authCredentialList property.
     * 
     * @return
     *     possible object is
     *     {@link AuthCredentialList }
     *     
     */
    public AuthCredentialList getAuthCredentialList() {
        return authCredentialList;
    }

    /**
     * Sets the value of the authCredentialList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthCredentialList }
     *     
     */
    public void setAuthCredentialList(AuthCredentialList value) {
        this.authCredentialList = value;
    }

    /**
     * Gets the value of the auto property.
     * 
     * @return
     *     possible object is
     *     {@link Auto }
     *     
     */
    public Auto getAuto() {
        return auto;
    }

    /**
     * Sets the value of the auto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Auto }
     *     
     */
    public void setAuto(Auto value) {
        this.auto = value;
    }

    /**
     * Gets the value of the autoRegEphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoRegEphone() {
        return autoRegEphone;
    }

    /**
     * Sets the value of the autoRegEphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoRegEphone(String value) {
        this.autoRegEphone = value;
    }

    /**
     * Gets the value of the bulkSpeedDialList property.
     * 
     * @return
     *     possible object is
     *     {@link BulkSpeedDialList }
     *     
     */
    public BulkSpeedDialList getBulkSpeedDialList() {
        return bulkSpeedDialList;
    }

    /**
     * Sets the value of the bulkSpeedDialList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BulkSpeedDialList }
     *     
     */
    public void setBulkSpeedDialList(BulkSpeedDialList value) {
        this.bulkSpeedDialList = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the globalCallForward property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalCallForward }
     *     
     */
    public GlobalCallForward getGlobalCallForward() {
        return globalCallForward;
    }

    /**
     * Sets the value of the globalCallForward property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalCallForward }
     *     
     */
    public void setGlobalCallForward(GlobalCallForward value) {
        this.globalCallForward = value;
    }

    /**
     * Gets the value of the callPark property.
     * 
     * @return
     *     possible object is
     *     {@link CallPark }
     *     
     */
    public CallPark getCallPark() {
        return callPark;
    }

    /**
     * Sets the value of the callPark property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallPark }
     *     
     */
    public void setCallPark(CallPark value) {
        this.callPark = value;
    }

    /**
     * Gets the value of the callerId property.
     * 
     * @return
     *     possible object is
     *     {@link CallerId }
     *     
     */
    public CallerId getCallerId() {
        return callerId;
    }

    /**
     * Sets the value of the callerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallerId }
     *     
     */
    public void setCallerId(CallerId value) {
        this.callerId = value;
    }

    /**
     * Gets the value of the callingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CallingNumber }
     *     
     */
    public CallingNumber getCallingNumber() {
        return callingNumber;
    }

    /**
     * Sets the value of the callingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallingNumber }
     *     
     */
    public void setCallingNumber(CallingNumber value) {
        this.callingNumber = value;
    }

    /**
     * Gets the value of the cnfFile property.
     * 
     * @return
     *     possible object is
     *     {@link CnfFile }
     *     
     */
    public CnfFile getCnfFile() {
        return cnfFile;
    }

    /**
     * Sets the value of the cnfFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CnfFile }
     *     
     */
    public void setCnfFile(CnfFile value) {
        this.cnfFile = value;
    }

    /**
     * Gets the value of the defaultCodec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCodec() {
        return defaultCodec;
    }

    /**
     * Sets the value of the defaultCodec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCodec(String value) {
        this.defaultCodec = value;
    }

    /**
     * Gets the value of the conference property.
     * 
     * @return
     *     possible object is
     *     {@link Conference }
     *     
     */
    public Conference getConference() {
        return conference;
    }

    /**
     * Sets the value of the conference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conference }
     *     
     */
    public void setConference(Conference value) {
        this.conference = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the deviceSecurityMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceSecurityMode() {
        return deviceSecurityMode;
    }

    /**
     * Sets the value of the deviceSecurityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceSecurityMode(String value) {
        this.deviceSecurityMode = value;
    }

    /**
     * Gets the value of the dialplanPatternList property.
     * 
     * @return
     *     possible object is
     *     {@link DialplanPatternList }
     *     
     */
    public DialplanPatternList getDialplanPatternList() {
        return dialplanPatternList;
    }

    /**
     * Sets the value of the dialplanPatternList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialplanPatternList }
     *     
     */
    public void setDialplanPatternList(DialplanPatternList value) {
        this.dialplanPatternList = value;
    }

    /**
     * Gets the value of the directory property.
     * 
     * @return
     *     possible object is
     *     {@link Directory }
     *     
     */
    public Directory getDirectory() {
        return directory;
    }

    /**
     * Sets the value of the directory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directory }
     *     
     */
    public void setDirectory(Directory value) {
        this.directory = value;
    }

    /**
     * Gets the value of the dnWebedit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnWebedit() {
        return dnWebedit;
    }

    /**
     * Sets the value of the dnWebedit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnWebedit(String value) {
        this.dnWebedit = value;
    }

    /**
     * Gets the value of the em property.
     * 
     * @return
     *     possible object is
     *     {@link Em }
     *     
     */
    public Em getEm() {
        return em;
    }

    /**
     * Sets the value of the em property.
     * 
     * @param value
     *     allowed object is
     *     {@link Em }
     *     
     */
    public void setEm(Em value) {
        this.em = value;
    }

    /**
     * Gets the value of the ephoneReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEphoneReg() {
        return ephoneReg;
    }

    /**
     * Sets the value of the ephoneReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEphoneReg(String value) {
        this.ephoneReg = value;
    }

    /**
     * Gets the value of the extensionAssigner property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionAssigner }
     *     
     */
    public ExtensionAssigner getExtensionAssigner() {
        return extensionAssigner;
    }

    /**
     * Sets the value of the extensionAssigner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionAssigner }
     *     
     */
    public void setExtensionAssigner(ExtensionAssigner value) {
        this.extensionAssigner = value;
    }

    /**
     * Gets the value of the fac property.
     * 
     * @return
     *     possible object is
     *     {@link Fac }
     *     
     */
    public Fac getFac() {
        return fac;
    }

    /**
     * Sets the value of the fac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fac }
     *     
     */
    public void setFac(Fac value) {
        this.fac = value;
    }

    /**
     * Gets the value of the fxo property.
     * 
     * @return
     *     possible object is
     *     {@link Fxo }
     *     
     */
    public Fxo getFxo() {
        return fxo;
    }

    /**
     * Sets the value of the fxo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fxo }
     *     
     */
    public void setFxo(Fxo value) {
        this.fxo = value;
    }

    /**
     * Gets the value of the huntGroup property.
     * 
     * @return
     *     possible object is
     *     {@link HuntGroup }
     *     
     */
    public HuntGroup getHuntGroup() {
        return huntGroup;
    }

    /**
     * Sets the value of the huntGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link HuntGroup }
     *     
     */
    public void setHuntGroup(HuntGroup value) {
        this.huntGroup = value;
    }

    /**
     * Gets the value of the internalCall property.
     * 
     * @return
     *     possible object is
     *     {@link InternalCall }
     *     
     */
    public InternalCall getInternalCall() {
        return internalCall;
    }

    /**
     * Sets the value of the internalCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalCall }
     *     
     */
    public void setInternalCall(InternalCall value) {
        this.internalCall = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link Ip }
     *     
     */
    public Ip getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ip }
     *     
     */
    public void setIp(Ip value) {
        this.ip = value;
    }

    /**
     * Gets the value of the keepalive property.
     * 
     * @return
     *     possible object is
     *     {@link Keepalive }
     *     
     */
    public Keepalive getKeepalive() {
        return keepalive;
    }

    /**
     * Sets the value of the keepalive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keepalive }
     *     
     */
    public void setKeepalive(Keepalive value) {
        this.keepalive = value;
    }

    /**
     * Gets the value of the liveRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveRecord() {
        return liveRecord;
    }

    /**
     * Sets the value of the liveRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveRecord(String value) {
        this.liveRecord = value;
    }

    /**
     * Gets the value of the loadList property.
     * 
     * @return
     *     possible object is
     *     {@link LoadList }
     *     
     */
    public LoadList getLoadList() {
        return loadList;
    }

    /**
     * Sets the value of the loadList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadList }
     *     
     */
    public void setLoadList(LoadList value) {
        this.loadList = value;
    }

    /**
     * Gets the value of the loadCfgFileList property.
     * 
     * @return
     *     possible object is
     *     {@link LoadCfgFileList }
     *     
     */
    public LoadCfgFileList getLoadCfgFileList() {
        return loadCfgFileList;
    }

    /**
     * Sets the value of the loadCfgFileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadCfgFileList }
     *     
     */
    public void setLoadCfgFileList(LoadCfgFileList value) {
        this.loadCfgFileList = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link Login }
     *     
     */
    public Login getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link Login }
     *     
     */
    public void setLogin(Login value) {
        this.login = value;
    }

    /**
     * Gets the value of the maxConferences property.
     * 
     * @return
     *     possible object is
     *     {@link MaxConferences }
     *     
     */
    public MaxConferences getMaxConferences() {
        return maxConferences;
    }

    /**
     * Sets the value of the maxConferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxConferences }
     *     
     */
    public void setMaxConferences(MaxConferences value) {
        this.maxConferences = value;
    }

    /**
     * Gets the value of the maxDn property.
     * 
     * @return
     *     possible object is
     *     {@link MaxDn }
     *     
     */
    public MaxDn getMaxDn() {
        return maxDn;
    }

    /**
     * Sets the value of the maxDn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxDn }
     *     
     */
    public void setMaxDn(MaxDn value) {
        this.maxDn = value;
    }

    /**
     * Gets the value of the maxEphones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxEphones() {
        return maxEphones;
    }

    /**
     * Sets the value of the maxEphones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxEphones(String value) {
        this.maxEphones = value;
    }

    /**
     * Gets the value of the maxRedirect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRedirect() {
        return maxRedirect;
    }

    /**
     * Sets the value of the maxRedirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRedirect(String value) {
        this.maxRedirect = value;
    }

    /**
     * Gets the value of the modem property.
     * 
     * @return
     *     possible object is
     *     {@link Modem }
     *     
     */
    public Modem getModem() {
        return modem;
    }

    /**
     * Sets the value of the modem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modem }
     *     
     */
    public void setModem(Modem value) {
        this.modem = value;
    }

    /**
     * Gets the value of the mohFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMohFile() {
        return mohFile;
    }

    /**
     * Sets the value of the mohFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMohFile(String value) {
        this.mohFile = value;
    }

    /**
     * Gets the value of the mohFileBuffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMohFileBuffer() {
        return mohFileBuffer;
    }

    /**
     * Sets the value of the mohFileBuffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMohFileBuffer(String value) {
        this.mohFileBuffer = value;
    }

    /**
     * Gets the value of the multicast property.
     * 
     * @return
     *     possible object is
     *     {@link Multicast }
     *     
     */
    public Multicast getMulticast() {
        return multicast;
    }

    /**
     * Sets the value of the multicast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multicast }
     *     
     */
    public void setMulticast(Multicast value) {
        this.multicast = value;
    }

    /**
     * Gets the value of the mwiServer property.
     * 
     * @return
     *     possible object is
     *     {@link MwiServer }
     *     
     */
    public MwiServer getMwiServer() {
        return mwiServer;
    }

    /**
     * Sets the value of the mwiServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link MwiServer }
     *     
     */
    public void setMwiServer(MwiServer value) {
        this.mwiServer = value;
    }

    /**
     * Gets the value of the networkLocaleList property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkLocaleList }
     *     
     */
    public NetworkLocaleList getNetworkLocaleList() {
        return networkLocaleList;
    }

    /**
     * Sets the value of the networkLocaleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkLocaleList }
     *     
     */
    public void setNetworkLocaleList(NetworkLocaleList value) {
        this.networkLocaleList = value;
    }

    /**
     * Gets the value of the nightService property.
     * 
     * @return
     *     possible object is
     *     {@link NightService }
     *     
     */
    public NightService getNightService() {
        return nightService;
    }

    /**
     * Sets the value of the nightService property.
     * 
     * @param value
     *     allowed object is
     *     {@link NightService }
     *     
     */
    public void setNightService(NightService value) {
        this.nightService = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPin() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPin(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the pinOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinOverride() {
        return pinOverride;
    }

    /**
     * Sets the value of the pinOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinOverride(String value) {
        this.pinOverride = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacy(String value) {
        this.privacy = value;
    }

    /**
     * Gets the value of the privacyOnHold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyOnHold() {
        return privacyOnHold;
    }

    /**
     * Sets the value of the privacyOnHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyOnHold(String value) {
        this.privacyOnHold = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link Protocol }
     *     
     */
    public Protocol getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link Protocol }
     *     
     */
    public void setProtocol(Protocol value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the sdspfarm property.
     * 
     * @return
     *     possible object is
     *     {@link Sdspfarm }
     *     
     */
    public Sdspfarm getSdspfarm() {
        return sdspfarm;
    }

    /**
     * Sets the value of the sdspfarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sdspfarm }
     *     
     */
    public void setSdspfarm(Sdspfarm value) {
        this.sdspfarm = value;
    }

    /**
     * Gets the value of the secondaryDialtone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryDialtone() {
        return secondaryDialtone;
    }

    /**
     * Sets the value of the secondaryDialtone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryDialtone(String value) {
        this.secondaryDialtone = value;
    }

    /**
     * Gets the value of the secureSignaling property.
     * 
     * @return
     *     possible object is
     *     {@link SecureSignaling }
     *     
     */
    public SecureSignaling getSecureSignaling() {
        return secureSignaling;
    }

    /**
     * Sets the value of the secureSignaling property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecureSignaling }
     *     
     */
    public void setSecureSignaling(SecureSignaling value) {
        this.secureSignaling = value;
    }

    /**
     * Gets the value of the serverSecurityMode property.
     * 
     * @return
     *     possible object is
     *     {@link ServerSecurityMode }
     *     
     */
    public ServerSecurityMode getServerSecurityMode() {
        return serverSecurityMode;
    }

    /**
     * Sets the value of the serverSecurityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerSecurityMode }
     *     
     */
    public void setServerSecurityMode(ServerSecurityMode value) {
        this.serverSecurityMode = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Service }
     *     
     */
    public Service getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service }
     *     
     */
    public void setService(Service value) {
        this.service = value;
    }

    /**
     * Gets the value of the ssh property.
     * 
     * @return
     *     possible object is
     *     {@link Ssh }
     *     
     */
    public Ssh getSsh() {
        return ssh;
    }

    /**
     * Sets the value of the ssh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ssh }
     *     
     */
    public void setSsh(Ssh value) {
        this.ssh = value;
    }

    /**
     * Gets the value of the standby property.
     * 
     * @return
     *     possible object is
     *     {@link Standby }
     *     
     */
    public Standby getStandby() {
        return standby;
    }

    /**
     * Sets the value of the standby property.
     * 
     * @param value
     *     allowed object is
     *     {@link Standby }
     *     
     */
    public void setStandby(Standby value) {
        this.standby = value;
    }

    /**
     * Gets the value of the systemMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemMessage() {
        return systemMessage;
    }

    /**
     * Sets the value of the systemMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemMessage(String value) {
        this.systemMessage = value;
    }

    /**
     * Gets the value of the tftpServerCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link TftpServerCredentials }
     *     
     */
    public TftpServerCredentials getTftpServerCredentials() {
        return tftpServerCredentials;
    }

    /**
     * Sets the value of the tftpServerCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link TftpServerCredentials }
     *     
     */
    public void setTftpServerCredentials(TftpServerCredentials value) {
        this.tftpServerCredentials = value;
    }

    /**
     * Gets the value of the timeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFormat() {
        return timeFormat;
    }

    /**
     * Sets the value of the timeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFormat(String value) {
        this.timeFormat = value;
    }

    /**
     * Gets the value of the timeWebedit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeWebedit() {
        return timeWebedit;
    }

    /**
     * Sets the value of the timeWebedit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeWebedit(String value) {
        this.timeWebedit = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the timeouts property.
     * 
     * @return
     *     possible object is
     *     {@link Timeouts }
     *     
     */
    public Timeouts getTimeouts() {
        return timeouts;
    }

    /**
     * Sets the value of the timeouts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timeouts }
     *     
     */
    public void setTimeouts(Timeouts value) {
        this.timeouts = value;
    }

    /**
     * Gets the value of the transferDigitCollect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferDigitCollect() {
        return transferDigitCollect;
    }

    /**
     * Sets the value of the transferDigitCollect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferDigitCollect(String value) {
        this.transferDigitCollect = value;
    }

    /**
     * Gets the value of the transferPatternList property.
     * 
     * @return
     *     possible object is
     *     {@link TransferPatternList }
     *     
     */
    public TransferPatternList getTransferPatternList() {
        return transferPatternList;
    }

    /**
     * Sets the value of the transferPatternList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferPatternList }
     *     
     */
    public void setTransferPatternList(TransferPatternList value) {
        this.transferPatternList = value;
    }

    /**
     * Gets the value of the transferSystem property.
     * 
     * @return
     *     possible object is
     *     {@link TransferSystem }
     *     
     */
    public TransferSystem getTransferSystem() {
        return transferSystem;
    }

    /**
     * Sets the value of the transferSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferSystem }
     *     
     */
    public void setTransferSystem(TransferSystem value) {
        this.transferSystem = value;
    }

    /**
     * Gets the value of the trunkOptimizationPreConnect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrunkOptimizationPreConnect() {
        return trunkOptimizationPreConnect;
    }

    /**
     * Sets the value of the trunkOptimizationPreConnect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrunkOptimizationPreConnect(String value) {
        this.trunkOptimizationPreConnect = value;
    }

    /**
     * Gets the value of the urlList property.
     * 
     * @return
     *     possible object is
     *     {@link UrlList }
     *     
     */
    public UrlList getUrlList() {
        return urlList;
    }

    /**
     * Sets the value of the urlList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlList }
     *     
     */
    public void setUrlList(UrlList value) {
        this.urlList = value;
    }

    /**
     * Gets the value of the userLocaleList property.
     * 
     * @return
     *     possible object is
     *     {@link UserLocaleList }
     *     
     */
    public UserLocaleList getUserLocaleList() {
        return userLocaleList;
    }

    /**
     * Sets the value of the userLocaleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserLocaleList }
     *     
     */
    public void setUserLocaleList(UserLocaleList value) {
        this.userLocaleList = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link Video }
     *     
     */
    public Video getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link Video }
     *     
     */
    public void setVideo(Video value) {
        this.video = value;
    }

    /**
     * Gets the value of the voicemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoicemail() {
        return voicemail;
    }

    /**
     * Sets the value of the voicemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoicemail(String value) {
        this.voicemail = value;
    }

    /**
     * Gets the value of the web property.
     * 
     * @return
     *     possible object is
     *     {@link Web }
     *     
     */
    public Web getWeb() {
        return web;
    }

    /**
     * Sets the value of the web property.
     * 
     * @param value
     *     allowed object is
     *     {@link Web }
     *     
     */
    public void setWeb(Web value) {
        this.web = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link Xml }
     *     
     */
    public Xml getXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xml }
     *     
     */
    public void setXml(Xml value) {
        this.xml = value;
    }

}
