//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPresenceEnable"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMode"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISAllowSub"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISAllowWatch"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISMaxSubAllow"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSipUaPresenceStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isPresenceEnable",
    "isMode",
    "isAllowSub",
    "isAllowWatch",
    "isMaxSubAllow",
    "isSipUaPresenceStatus"
})
@XmlRootElement(name = "ISPresenceGlobal")
public class ISPresenceGlobal {

    @XmlElement(name = "ISPresenceEnable", required = true)
    protected String isPresenceEnable;
    @XmlElement(name = "ISMode", required = true)
    protected String isMode;
    @XmlElement(name = "ISAllowSub", required = true)
    protected String isAllowSub;
    @XmlElement(name = "ISAllowWatch", required = true)
    protected String isAllowWatch;
    @XmlElement(name = "ISMaxSubAllow", required = true)
    protected String isMaxSubAllow;
    @XmlElement(name = "ISSipUaPresenceStatus", required = true)
    protected String isSipUaPresenceStatus;

    /**
     * Gets the value of the isPresenceEnable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPresenceEnable() {
        return isPresenceEnable;
    }

    /**
     * Sets the value of the isPresenceEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPresenceEnable(String value) {
        this.isPresenceEnable = value;
    }

    /**
     * Gets the value of the isMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMode() {
        return isMode;
    }

    /**
     * Sets the value of the isMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMode(String value) {
        this.isMode = value;
    }

    /**
     * Gets the value of the isAllowSub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISAllowSub() {
        return isAllowSub;
    }

    /**
     * Sets the value of the isAllowSub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISAllowSub(String value) {
        this.isAllowSub = value;
    }

    /**
     * Gets the value of the isAllowWatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISAllowWatch() {
        return isAllowWatch;
    }

    /**
     * Sets the value of the isAllowWatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISAllowWatch(String value) {
        this.isAllowWatch = value;
    }

    /**
     * Gets the value of the isMaxSubAllow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISMaxSubAllow() {
        return isMaxSubAllow;
    }

    /**
     * Sets the value of the isMaxSubAllow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISMaxSubAllow(String value) {
        this.isMaxSubAllow = value;
    }

    /**
     * Gets the value of the isSipUaPresenceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSipUaPresenceStatus() {
        return isSipUaPresenceStatus;
    }

    /**
     * Sets the value of the isSipUaPresenceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSipUaPresenceStatus(String value) {
        this.isSipUaPresenceStatus = value;
    }

}
