//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPoolID"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}ISDevMac"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISSessionServerID"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISDevAddr"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISSipPhoneLineList"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISPoolMaxRegistration"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISPoolDtmfRelay"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISDevCodec"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isPoolID",
    "isDevMac",
    "isSessionServerID",
    "isDevAddr",
    "isSipPhoneLineList",
    "isPoolMaxRegistration",
    "isPoolDtmfRelay",
    "isDevCodec"
})
@XmlRootElement(name = "ISSipDevice")
public class ISSipDevice {

    @XmlElement(name = "ISPoolID", required = true)
    protected String isPoolID;
    @XmlElement(name = "ISDevMac")
    protected String isDevMac;
    @XmlElement(name = "ISSessionServerID")
    protected String isSessionServerID;
    @XmlElement(name = "ISDevAddr")
    protected ISDevAddr isDevAddr;
    @XmlElement(name = "ISSipPhoneLineList")
    protected ISSipPhoneLineList isSipPhoneLineList;
    @XmlElement(name = "ISPoolMaxRegistration")
    protected String isPoolMaxRegistration;
    @XmlElement(name = "ISPoolDtmfRelay")
    protected String isPoolDtmfRelay;
    @XmlElement(name = "ISDevCodec")
    protected String isDevCodec;

    /**
     * Gets the value of the isPoolID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPoolID() {
        return isPoolID;
    }

    /**
     * Sets the value of the isPoolID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPoolID(String value) {
        this.isPoolID = value;
    }

    /**
     * Gets the value of the isDevMac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDevMac() {
        return isDevMac;
    }

    /**
     * Sets the value of the isDevMac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDevMac(String value) {
        this.isDevMac = value;
    }

    /**
     * Gets the value of the isSessionServerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSessionServerID() {
        return isSessionServerID;
    }

    /**
     * Sets the value of the isSessionServerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSessionServerID(String value) {
        this.isSessionServerID = value;
    }

    /**
     * Gets the value of the isDevAddr property.
     * 
     * @return
     *     possible object is
     *     {@link ISDevAddr }
     *     
     */
    public ISDevAddr getISDevAddr() {
        return isDevAddr;
    }

    /**
     * Sets the value of the isDevAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDevAddr }
     *     
     */
    public void setISDevAddr(ISDevAddr value) {
        this.isDevAddr = value;
    }

    /**
     * Gets the value of the isSipPhoneLineList property.
     * 
     * @return
     *     possible object is
     *     {@link ISSipPhoneLineList }
     *     
     */
    public ISSipPhoneLineList getISSipPhoneLineList() {
        return isSipPhoneLineList;
    }

    /**
     * Sets the value of the isSipPhoneLineList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSipPhoneLineList }
     *     
     */
    public void setISSipPhoneLineList(ISSipPhoneLineList value) {
        this.isSipPhoneLineList = value;
    }

    /**
     * Gets the value of the isPoolMaxRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPoolMaxRegistration() {
        return isPoolMaxRegistration;
    }

    /**
     * Sets the value of the isPoolMaxRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPoolMaxRegistration(String value) {
        this.isPoolMaxRegistration = value;
    }

    /**
     * Gets the value of the isPoolDtmfRelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPoolDtmfRelay() {
        return isPoolDtmfRelay;
    }

    /**
     * Sets the value of the isPoolDtmfRelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPoolDtmfRelay(String value) {
        this.isPoolDtmfRelay = value;
    }

    /**
     * Gets the value of the isDevCodec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDevCodec() {
        return isDevCodec;
    }

    /**
     * Sets the value of the isDevCodec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDevCodec(String value) {
        this.isDevCodec = value;
    }

}
