//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISUserProfileID"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}ISuserID"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISpassword"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISuserPin"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISPrivacyButton"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISuserMaxIdleTime"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}SpeedDials"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}UserNumbers"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISuserCurrentPhone"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isUserProfileID",
    "iSuserID",
    "iSpassword",
    "iSuserPin",
    "isPrivacyButton",
    "iSuserMaxIdleTime",
    "speedDials",
    "userNumbers",
    "iSuserCurrentPhone"
})
@XmlRootElement(name = "ISUserProfile")
public class ISUserProfile {

    @XmlElement(name = "ISUserProfileID", required = true)
    protected String isUserProfileID;
    @XmlElement(name = "ISuserID")
    protected String iSuserID;
    @XmlElement(name = "ISpassword")
    protected String iSpassword;
    @XmlElement(name = "ISuserPin")
    protected String iSuserPin;
    @XmlElement(name = "ISPrivacyButton")
    protected String isPrivacyButton;
    @XmlElement(name = "ISuserMaxIdleTime")
    protected String iSuserMaxIdleTime;
    @XmlElement(name = "SpeedDials")
    protected SpeedDials speedDials;
    @XmlElement(name = "UserNumbers")
    protected UserNumbers userNumbers;
    @XmlElement(name = "ISuserCurrentPhone")
    protected ISuserCurrentPhone iSuserCurrentPhone;

    /**
     * Gets the value of the isUserProfileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISUserProfileID() {
        return isUserProfileID;
    }

    /**
     * Sets the value of the isUserProfileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISUserProfileID(String value) {
        this.isUserProfileID = value;
    }

    /**
     * Gets the value of the iSuserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISuserID() {
        return iSuserID;
    }

    /**
     * Sets the value of the iSuserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISuserID(String value) {
        this.iSuserID = value;
    }

    /**
     * Gets the value of the iSpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISpassword() {
        return iSpassword;
    }

    /**
     * Sets the value of the iSpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISpassword(String value) {
        this.iSpassword = value;
    }

    /**
     * Gets the value of the iSuserPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISuserPin() {
        return iSuserPin;
    }

    /**
     * Sets the value of the iSuserPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISuserPin(String value) {
        this.iSuserPin = value;
    }

    /**
     * Gets the value of the isPrivacyButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPrivacyButton() {
        return isPrivacyButton;
    }

    /**
     * Sets the value of the isPrivacyButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPrivacyButton(String value) {
        this.isPrivacyButton = value;
    }

    /**
     * Gets the value of the iSuserMaxIdleTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISuserMaxIdleTime() {
        return iSuserMaxIdleTime;
    }

    /**
     * Sets the value of the iSuserMaxIdleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISuserMaxIdleTime(String value) {
        this.iSuserMaxIdleTime = value;
    }

    /**
     * Gets the value of the speedDials property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedDials }
     *     
     */
    public SpeedDials getSpeedDials() {
        return speedDials;
    }

    /**
     * Sets the value of the speedDials property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedDials }
     *     
     */
    public void setSpeedDials(SpeedDials value) {
        this.speedDials = value;
    }

    /**
     * Gets the value of the userNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link UserNumbers }
     *     
     */
    public UserNumbers getUserNumbers() {
        return userNumbers;
    }

    /**
     * Sets the value of the userNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserNumbers }
     *     
     */
    public void setUserNumbers(UserNumbers value) {
        this.userNumbers = value;
    }

    /**
     * Gets the value of the iSuserCurrentPhone property.
     * 
     * @return
     *     possible object is
     *     {@link ISuserCurrentPhone }
     *     
     */
    public ISuserCurrentPhone getISuserCurrentPhone() {
        return iSuserCurrentPhone;
    }

    /**
     * Sets the value of the iSuserCurrentPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISuserCurrentPhone }
     *     
     */
    public void setISuserCurrentPhone(ISuserCurrentPhone value) {
        this.iSuserCurrentPhone = value;
    }

}
