//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupID"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupType"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupPilotNumber"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupPilotPeerTag"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupPilotPreference"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupSecPilotNumber"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupSecPilotPeerTag"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupSecPilotPreference"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupListSize"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupListNums"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupFinalNum"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupTimeout"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroupHops"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isVoiceHuntGroupID",
    "isVoiceHuntGroupType",
    "isVoiceHuntGroupPilotNumber",
    "isVoiceHuntGroupPilotPeerTag",
    "isVoiceHuntGroupPilotPreference",
    "isVoiceHuntGroupSecPilotNumber",
    "isVoiceHuntGroupSecPilotPeerTag",
    "isVoiceHuntGroupSecPilotPreference",
    "isVoiceHuntGroupListSize",
    "isVoiceHuntGroupListNums",
    "isVoiceHuntGroupFinalNum",
    "isVoiceHuntGroupTimeout",
    "isVoiceHuntGroupHops"
})
@XmlRootElement(name = "ISVoiceHuntGroup")
public class ISVoiceHuntGroup {

    @XmlElement(name = "ISVoiceHuntGroupID", required = true)
    protected String isVoiceHuntGroupID;
    @XmlElement(name = "ISVoiceHuntGroupType")
    protected String isVoiceHuntGroupType;
    @XmlElement(name = "ISVoiceHuntGroupPilotNumber")
    protected String isVoiceHuntGroupPilotNumber;
    @XmlElement(name = "ISVoiceHuntGroupPilotPeerTag")
    protected String isVoiceHuntGroupPilotPeerTag;
    @XmlElement(name = "ISVoiceHuntGroupPilotPreference")
    protected String isVoiceHuntGroupPilotPreference;
    @XmlElement(name = "ISVoiceHuntGroupSecPilotNumber")
    protected String isVoiceHuntGroupSecPilotNumber;
    @XmlElement(name = "ISVoiceHuntGroupSecPilotPeerTag")
    protected String isVoiceHuntGroupSecPilotPeerTag;
    @XmlElement(name = "ISVoiceHuntGroupSecPilotPreference")
    protected String isVoiceHuntGroupSecPilotPreference;
    @XmlElement(name = "ISVoiceHuntGroupListSize")
    protected String isVoiceHuntGroupListSize;
    @XmlElement(name = "ISVoiceHuntGroupListNums")
    protected ISVoiceHuntGroupListNums isVoiceHuntGroupListNums;
    @XmlElement(name = "ISVoiceHuntGroupFinalNum")
    protected String isVoiceHuntGroupFinalNum;
    @XmlElement(name = "ISVoiceHuntGroupTimeout")
    protected String isVoiceHuntGroupTimeout;
    @XmlElement(name = "ISVoiceHuntGroupHops")
    protected String isVoiceHuntGroupHops;

    /**
     * Gets the value of the isVoiceHuntGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupID() {
        return isVoiceHuntGroupID;
    }

    /**
     * Sets the value of the isVoiceHuntGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupID(String value) {
        this.isVoiceHuntGroupID = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupType() {
        return isVoiceHuntGroupType;
    }

    /**
     * Sets the value of the isVoiceHuntGroupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupType(String value) {
        this.isVoiceHuntGroupType = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupPilotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupPilotNumber() {
        return isVoiceHuntGroupPilotNumber;
    }

    /**
     * Sets the value of the isVoiceHuntGroupPilotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupPilotNumber(String value) {
        this.isVoiceHuntGroupPilotNumber = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupPilotPeerTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupPilotPeerTag() {
        return isVoiceHuntGroupPilotPeerTag;
    }

    /**
     * Sets the value of the isVoiceHuntGroupPilotPeerTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupPilotPeerTag(String value) {
        this.isVoiceHuntGroupPilotPeerTag = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupPilotPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupPilotPreference() {
        return isVoiceHuntGroupPilotPreference;
    }

    /**
     * Sets the value of the isVoiceHuntGroupPilotPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupPilotPreference(String value) {
        this.isVoiceHuntGroupPilotPreference = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupSecPilotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupSecPilotNumber() {
        return isVoiceHuntGroupSecPilotNumber;
    }

    /**
     * Sets the value of the isVoiceHuntGroupSecPilotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupSecPilotNumber(String value) {
        this.isVoiceHuntGroupSecPilotNumber = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupSecPilotPeerTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupSecPilotPeerTag() {
        return isVoiceHuntGroupSecPilotPeerTag;
    }

    /**
     * Sets the value of the isVoiceHuntGroupSecPilotPeerTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupSecPilotPeerTag(String value) {
        this.isVoiceHuntGroupSecPilotPeerTag = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupSecPilotPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupSecPilotPreference() {
        return isVoiceHuntGroupSecPilotPreference;
    }

    /**
     * Sets the value of the isVoiceHuntGroupSecPilotPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupSecPilotPreference(String value) {
        this.isVoiceHuntGroupSecPilotPreference = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupListSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupListSize() {
        return isVoiceHuntGroupListSize;
    }

    /**
     * Sets the value of the isVoiceHuntGroupListSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupListSize(String value) {
        this.isVoiceHuntGroupListSize = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupListNums property.
     * 
     * @return
     *     possible object is
     *     {@link ISVoiceHuntGroupListNums }
     *     
     */
    public ISVoiceHuntGroupListNums getISVoiceHuntGroupListNums() {
        return isVoiceHuntGroupListNums;
    }

    /**
     * Sets the value of the isVoiceHuntGroupListNums property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISVoiceHuntGroupListNums }
     *     
     */
    public void setISVoiceHuntGroupListNums(ISVoiceHuntGroupListNums value) {
        this.isVoiceHuntGroupListNums = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupFinalNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupFinalNum() {
        return isVoiceHuntGroupFinalNum;
    }

    /**
     * Sets the value of the isVoiceHuntGroupFinalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupFinalNum(String value) {
        this.isVoiceHuntGroupFinalNum = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupTimeout() {
        return isVoiceHuntGroupTimeout;
    }

    /**
     * Sets the value of the isVoiceHuntGroupTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupTimeout(String value) {
        this.isVoiceHuntGroupTimeout = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroupHops property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVoiceHuntGroupHops() {
        return isVoiceHuntGroupHops;
    }

    /**
     * Sets the value of the isVoiceHuntGroupHops property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVoiceHuntGroupHops(String value) {
        this.isVoiceHuntGroupHops = value;
    }

}
