//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}hangup"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}drop-last"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}endcall"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}local-only"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hangup",
    "dropLast",
    "endcall",
    "localOnly"
})
@XmlRootElement(name = "keep-conference")
public class KeepConference {

    @XmlElement(required = true)
    protected String hangup;
    @XmlElement(name = "drop-last", required = true)
    protected String dropLast;
    @XmlElement(required = true)
    protected String endcall;
    @XmlElement(name = "local-only", required = true)
    protected String localOnly;

    /**
     * Gets the value of the hangup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHangup() {
        return hangup;
    }

    /**
     * Sets the value of the hangup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHangup(String value) {
        this.hangup = value;
    }

    /**
     * Gets the value of the dropLast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropLast() {
        return dropLast;
    }

    /**
     * Sets the value of the dropLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropLast(String value) {
        this.dropLast = value;
    }

    /**
     * Gets the value of the endcall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndcall() {
        return endcall;
    }

    /**
     * Sets the value of the endcall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndcall(String value) {
        this.endcall = value;
    }

    /**
     * Gets the value of the localOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalOnly() {
        return localOnly;
    }

    /**
     * Sets the value of the localOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalOnly(String value) {
        this.localOnly = value;
    }

}
