//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}TFTP"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}flash"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tftp",
    "flash"
})
@XmlRootElement(name = "location")
public class Location {

    @XmlElement(name = "TFTP", required = true)
    protected String tftp;
    @XmlElement(required = true)
    protected String flash;

    /**
     * Gets the value of the tftp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTFTP() {
        return tftp;
    }

    /**
     * Sets the value of the tftp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTFTP(String value) {
        this.tftp = value;
    }

    /**
     * Gets the value of the flash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlash() {
        return flash;
    }

    /**
     * Sets the value of the flash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlash(String value) {
        this.flash = value;
    }

}
