//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}dn"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}auto-con"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}loopback-codec"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}forward"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}prefix"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}retry"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}strip"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}suffix"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dn",
    "autoCon",
    "loopbackCodec",
    "forward",
    "prefix",
    "retry",
    "strip",
    "suffix"
})
@XmlRootElement(name = "loopback-dn")
public class LoopbackDn {

    @XmlElement(required = true)
    protected String dn;
    @XmlElement(name = "auto-con", required = true)
    protected String autoCon;
    @XmlElement(name = "loopback-codec", required = true)
    protected String loopbackCodec;
    @XmlElement(required = true)
    protected String forward;
    @XmlElement(required = true)
    protected String prefix;
    @XmlElement(required = true)
    protected String retry;
    @XmlElement(required = true)
    protected String strip;
    @XmlElement(required = true)
    protected String suffix;

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the autoCon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoCon() {
        return autoCon;
    }

    /**
     * Sets the value of the autoCon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoCon(String value) {
        this.autoCon = value;
    }

    /**
     * Gets the value of the loopbackCodec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopbackCodec() {
        return loopbackCodec;
    }

    /**
     * Sets the value of the loopbackCodec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopbackCodec(String value) {
        this.loopbackCodec = value;
    }

    /**
     * Gets the value of the forward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForward() {
        return forward;
    }

    /**
     * Sets the value of the forward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForward(String value) {
        this.forward = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetry(String value) {
        this.retry = value;
    }

    /**
     * Gets the value of the strip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrip() {
        return strip;
    }

    /**
     * Sets the value of the strip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrip(String value) {
        this.strip = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

}
