//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}passthrough"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}relay_sse"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}relay_sprt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "passthrough",
    "relaySse",
    "relaySprt"
})
@XmlRootElement(name = "modem")
public class Modem {

    @XmlElement(required = true)
    protected Passthrough passthrough;
    @XmlElement(name = "relay_sse", required = true)
    protected RelaySse relaySse;
    @XmlElement(name = "relay_sprt", required = true)
    protected RelaySprt relaySprt;

    /**
     * Gets the value of the passthrough property.
     * 
     * @return
     *     possible object is
     *     {@link Passthrough }
     *     
     */
    public Passthrough getPassthrough() {
        return passthrough;
    }

    /**
     * Sets the value of the passthrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passthrough }
     *     
     */
    public void setPassthrough(Passthrough value) {
        this.passthrough = value;
    }

    /**
     * Gets the value of the relaySse property.
     * 
     * @return
     *     possible object is
     *     {@link RelaySse }
     *     
     */
    public RelaySse getRelaySse() {
        return relaySse;
    }

    /**
     * Sets the value of the relaySse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelaySse }
     *     
     */
    public void setRelaySse(RelaySse value) {
        this.relaySse = value;
    }

    /**
     * Gets the value of the relaySprt property.
     * 
     * @return
     *     possible object is
     *     {@link RelaySprt }
     *     
     */
    public RelaySprt getRelaySprt() {
        return relaySprt;
    }

    /**
     * Sets the value of the relaySprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelaySprt }
     *     
     */
    public void setRelaySprt(RelaySprt value) {
        this.relaySprt = value;
    }

}
