//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}prefix"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}reg-e164"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}relay"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prefix",
    "regE164",
    "relay"
})
@XmlRootElement(name = "mwi-server")
public class MwiServer {

    @XmlElement(required = true)
    protected String prefix;
    @XmlElement(name = "reg-e164", required = true)
    protected String regE164;
    @XmlElement(required = true)
    protected String relay;

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the regE164 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegE164() {
        return regE164;
    }

    /**
     * Sets the value of the regE164 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegE164(String value) {
        this.regE164 = value;
    }

    /**
     * Gets the value of the relay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelay() {
        return relay;
    }

    /**
     * Sets the value of the relay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelay(String value) {
        this.relay = value;
    }

}
