//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 10:53:48 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "cisco_cme_xml_namespace", 
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)


package com.cisco.cme.custom.xml;
