//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}directed"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}reserved-for"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}reservation-group"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}timeout"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}limit"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}notify"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}only"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}transfer_destination"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}recall"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}alternate"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}retry"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}retry_limit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "directed",
    "reservedFor",
    "reservationGroup",
    "timeout",
    "limit",
    "notify",
    "only",
    "transferDestination",
    "recall",
    "alternate",
    "retry",
    "retryLimit"
})
@XmlRootElement(name = "park-slot")
public class ParkSlot {

    @XmlElement(required = true)
    protected String directed;
    @XmlElement(name = "reserved-for", required = true)
    protected String reservedFor;
    @XmlElement(name = "reservation-group", required = true)
    protected String reservationGroup;
    @XmlElement(required = true)
    protected String timeout;
    @XmlElement(required = true)
    protected String limit;
    @XmlElement(required = true)
    protected String notify;
    @XmlElement(required = true)
    protected String only;
    @XmlElement(name = "transfer_destination", required = true)
    protected String transferDestination;
    @XmlElement(required = true)
    protected String recall;
    @XmlElement(required = true)
    protected Alternate alternate;
    @XmlElement(required = true)
    protected String retry;
    @XmlElement(name = "retry_limit", required = true)
    protected String retryLimit;

    /**
     * Gets the value of the directed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirected() {
        return directed;
    }

    /**
     * Sets the value of the directed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirected(String value) {
        this.directed = value;
    }

    /**
     * Gets the value of the reservedFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservedFor() {
        return reservedFor;
    }

    /**
     * Sets the value of the reservedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservedFor(String value) {
        this.reservedFor = value;
    }

    /**
     * Gets the value of the reservationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationGroup() {
        return reservationGroup;
    }

    /**
     * Sets the value of the reservationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationGroup(String value) {
        this.reservationGroup = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimit(String value) {
        this.limit = value;
    }

    /**
     * Gets the value of the notify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotify() {
        return notify;
    }

    /**
     * Sets the value of the notify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotify(String value) {
        this.notify = value;
    }

    /**
     * Gets the value of the only property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnly() {
        return only;
    }

    /**
     * Sets the value of the only property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnly(String value) {
        this.only = value;
    }

    /**
     * Gets the value of the transferDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferDestination() {
        return transferDestination;
    }

    /**
     * Sets the value of the transferDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferDestination(String value) {
        this.transferDestination = value;
    }

    /**
     * Gets the value of the recall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecall() {
        return recall;
    }

    /**
     * Sets the value of the recall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecall(String value) {
        this.recall = value;
    }

    /**
     * Gets the value of the alternate property.
     * 
     * @return
     *     possible object is
     *     {@link Alternate }
     *     
     */
    public Alternate getAlternate() {
        return alternate;
    }

    /**
     * Sets the value of the alternate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alternate }
     *     
     */
    public void setAlternate(Alternate value) {
        this.alternate = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetry(String value) {
        this.retry = value;
    }

    /**
     * Gets the value of the retryLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryLimit() {
        return retryLimit;
    }

    /**
     * Sets the value of the retryLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryLimit(String value) {
        this.retryLimit = value;
    }

}
