//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}index"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}phone_params"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}phone_text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "index",
    "phoneParams",
    "phoneText"
})
@XmlRootElement(name = "phone_item")
public class PhoneItem {

    @XmlElement(required = true)
    protected String index;
    @XmlElement(name = "phone_params", required = true)
    protected String phoneParams;
    @XmlElement(name = "phone_text", required = true)
    protected String phoneText;

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the phoneParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneParams() {
        return phoneParams;
    }

    /**
     * Sets the value of the phoneParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneParams(String value) {
        this.phoneParams = value;
    }

    /**
     * Gets the value of the phoneText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneText() {
        return phoneText;
    }

    /**
     * Sets the value of the phoneText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneText(String value) {
        this.phoneText = value;
    }

}
