//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}snr"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}speeddial-fastdial"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "snr",
    "speeddialFastdial"
})
@XmlRootElement(name = "phone-ui")
public class PhoneUi {

    @XmlElement(required = true)
    protected String snr;
    @XmlElement(name = "speeddial-fastdial", required = true)
    protected String speeddialFastdial;

    /**
     * Gets the value of the snr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnr() {
        return snr;
    }

    /**
     * Sets the value of the snr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnr(String value) {
        this.snr = value;
    }

    /**
     * Gets the value of the speeddialFastdial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeeddialFastdial() {
        return speeddialFastdial;
    }

    /**
     * Sets the value of the speeddialFastdial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeeddialFastdial(String value) {
        this.speeddialFastdial = value;
    }

}
