//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDeviceTemplates"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISDevices"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISError"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISExtensionTemplates"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISExtensions"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISGlobal"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISPresenceGlobal"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSaveConfigResult"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSessionServers"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSipDevices"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSipExtensions"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISSipGlobal"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISUserProfiles"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISUtilityDirectory"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISVoiceHuntGroups"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISexecCLIResult"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ISuser"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isDeviceTemplates",
    "isDevices",
    "isError",
    "isExtensionTemplates",
    "isExtensions",
    "isGlobal",
    "isPresenceGlobal",
    "isSaveConfigResult",
    "isSessionServers",
    "isSipDevices",
    "isSipExtensions",
    "isSipGlobal",
    "isUserProfiles",
    "isUtilityDirectory",
    "isVoiceHuntGroups",
    "iSexecCLIResult",
    "iSuser"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(name = "ISDeviceTemplates")
    protected ISDeviceTemplates isDeviceTemplates;
    @XmlElement(name = "ISDevices")
    protected ISDevices isDevices;
    @XmlElement(name = "ISError")
    protected ISError isError;
    @XmlElement(name = "ISExtensionTemplates")
    protected ISExtensionTemplates isExtensionTemplates;
    @XmlElement(name = "ISExtensions")
    protected ISExtensions isExtensions;
    @XmlElement(name = "ISGlobal")
    protected ISGlobal isGlobal;
    @XmlElement(name = "ISPresenceGlobal")
    protected ISPresenceGlobal isPresenceGlobal;
    @XmlElement(name = "ISSaveConfigResult")
    protected String isSaveConfigResult;
    @XmlElement(name = "ISSessionServers")
    protected ISSessionServers isSessionServers;
    @XmlElement(name = "ISSipDevices")
    protected ISSipDevices isSipDevices;
    @XmlElement(name = "ISSipExtensions")
    protected ISSipExtensions isSipExtensions;
    @XmlElement(name = "ISSipGlobal")
    protected ISSipGlobal isSipGlobal;
    @XmlElement(name = "ISUserProfiles")
    protected ISUserProfiles isUserProfiles;
    @XmlElement(name = "ISUtilityDirectory")
    protected ISUtilityDirectory isUtilityDirectory;
    @XmlElement(name = "ISVoiceHuntGroups")
    protected ISVoiceHuntGroups isVoiceHuntGroups;
    @XmlElement(name = "ISexecCLIResult")
    protected ISexecCLIResult iSexecCLIResult;
    @XmlElement(name = "ISuser")
    protected ISuser iSuser;

    /**
     * Gets the value of the isDeviceTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link ISDeviceTemplates }
     *     
     */
    public ISDeviceTemplates getISDeviceTemplates() {
        return isDeviceTemplates;
    }

    /**
     * Sets the value of the isDeviceTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDeviceTemplates }
     *     
     */
    public void setISDeviceTemplates(ISDeviceTemplates value) {
        this.isDeviceTemplates = value;
    }

    /**
     * Gets the value of the isDevices property.
     * 
     * @return
     *     possible object is
     *     {@link ISDevices }
     *     
     */
    public ISDevices getISDevices() {
        return isDevices;
    }

    /**
     * Sets the value of the isDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDevices }
     *     
     */
    public void setISDevices(ISDevices value) {
        this.isDevices = value;
    }

    /**
     * Gets the value of the isError property.
     * 
     * @return
     *     possible object is
     *     {@link ISError }
     *     
     */
    public ISError getISError() {
        return isError;
    }

    /**
     * Sets the value of the isError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISError }
     *     
     */
    public void setISError(ISError value) {
        this.isError = value;
    }

    /**
     * Gets the value of the isExtensionTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link ISExtensionTemplates }
     *     
     */
    public ISExtensionTemplates getISExtensionTemplates() {
        return isExtensionTemplates;
    }

    /**
     * Sets the value of the isExtensionTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISExtensionTemplates }
     *     
     */
    public void setISExtensionTemplates(ISExtensionTemplates value) {
        this.isExtensionTemplates = value;
    }

    /**
     * Gets the value of the isExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link ISExtensions }
     *     
     */
    public ISExtensions getISExtensions() {
        return isExtensions;
    }

    /**
     * Sets the value of the isExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISExtensions }
     *     
     */
    public void setISExtensions(ISExtensions value) {
        this.isExtensions = value;
    }

    /**
     * Gets the value of the isGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link ISGlobal }
     *     
     */
    public ISGlobal getISGlobal() {
        return isGlobal;
    }

    /**
     * Sets the value of the isGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISGlobal }
     *     
     */
    public void setISGlobal(ISGlobal value) {
        this.isGlobal = value;
    }

    /**
     * Gets the value of the isPresenceGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link ISPresenceGlobal }
     *     
     */
    public ISPresenceGlobal getISPresenceGlobal() {
        return isPresenceGlobal;
    }

    /**
     * Sets the value of the isPresenceGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISPresenceGlobal }
     *     
     */
    public void setISPresenceGlobal(ISPresenceGlobal value) {
        this.isPresenceGlobal = value;
    }

    /**
     * Gets the value of the isSaveConfigResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSaveConfigResult() {
        return isSaveConfigResult;
    }

    /**
     * Sets the value of the isSaveConfigResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSaveConfigResult(String value) {
        this.isSaveConfigResult = value;
    }

    /**
     * Gets the value of the isSessionServers property.
     * 
     * @return
     *     possible object is
     *     {@link ISSessionServers }
     *     
     */
    public ISSessionServers getISSessionServers() {
        return isSessionServers;
    }

    /**
     * Sets the value of the isSessionServers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSessionServers }
     *     
     */
    public void setISSessionServers(ISSessionServers value) {
        this.isSessionServers = value;
    }

    /**
     * Gets the value of the isSipDevices property.
     * 
     * @return
     *     possible object is
     *     {@link ISSipDevices }
     *     
     */
    public ISSipDevices getISSipDevices() {
        return isSipDevices;
    }

    /**
     * Sets the value of the isSipDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSipDevices }
     *     
     */
    public void setISSipDevices(ISSipDevices value) {
        this.isSipDevices = value;
    }

    /**
     * Gets the value of the isSipExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link ISSipExtensions }
     *     
     */
    public ISSipExtensions getISSipExtensions() {
        return isSipExtensions;
    }

    /**
     * Sets the value of the isSipExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSipExtensions }
     *     
     */
    public void setISSipExtensions(ISSipExtensions value) {
        this.isSipExtensions = value;
    }

    /**
     * Gets the value of the isSipGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link ISSipGlobal }
     *     
     */
    public ISSipGlobal getISSipGlobal() {
        return isSipGlobal;
    }

    /**
     * Sets the value of the isSipGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSipGlobal }
     *     
     */
    public void setISSipGlobal(ISSipGlobal value) {
        this.isSipGlobal = value;
    }

    /**
     * Gets the value of the isUserProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link ISUserProfiles }
     *     
     */
    public ISUserProfiles getISUserProfiles() {
        return isUserProfiles;
    }

    /**
     * Sets the value of the isUserProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISUserProfiles }
     *     
     */
    public void setISUserProfiles(ISUserProfiles value) {
        this.isUserProfiles = value;
    }

    /**
     * Gets the value of the isUtilityDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link ISUtilityDirectory }
     *     
     */
    public ISUtilityDirectory getISUtilityDirectory() {
        return isUtilityDirectory;
    }

    /**
     * Sets the value of the isUtilityDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISUtilityDirectory }
     *     
     */
    public void setISUtilityDirectory(ISUtilityDirectory value) {
        this.isUtilityDirectory = value;
    }

    /**
     * Gets the value of the isVoiceHuntGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ISVoiceHuntGroups }
     *     
     */
    public ISVoiceHuntGroups getISVoiceHuntGroups() {
        return isVoiceHuntGroups;
    }

    /**
     * Sets the value of the isVoiceHuntGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISVoiceHuntGroups }
     *     
     */
    public void setISVoiceHuntGroups(ISVoiceHuntGroups value) {
        this.isVoiceHuntGroups = value;
    }

    /**
     * Gets the value of the iSexecCLIResult property.
     * 
     * @return
     *     possible object is
     *     {@link ISexecCLIResult }
     *     
     */
    public ISexecCLIResult getISexecCLIResult() {
        return iSexecCLIResult;
    }

    /**
     * Sets the value of the iSexecCLIResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISexecCLIResult }
     *     
     */
    public void setISexecCLIResult(ISexecCLIResult value) {
        this.iSexecCLIResult = value;
    }

    /**
     * Gets the value of the iSuser property.
     * 
     * @return
     *     possible object is
     *     {@link ISuser }
     *     
     */
    public ISuser getISuser() {
        return iSuser;
    }

    /**
     * Sets the value of the iSuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISuser }
     *     
     */
    public void setISuser(ISuser value) {
        this.iSuser = value;
    }

}
