//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}primary"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}port"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}secondary"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}rehome"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}strict-match"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primary",
    "port",
    "secondary",
    "rehome",
    "strictMatch"
})
@XmlRootElement(name = "source-address")
public class SourceAddress {

    @XmlElement(required = true)
    protected String primary;
    @XmlElement(required = true)
    protected String port;
    @XmlElement(required = true)
    protected String secondary;
    @XmlElement(required = true)
    protected String rehome;
    @XmlElement(name = "strict-match", required = true)
    protected String strictMatch;

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimary(String value) {
        this.primary = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondary() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondary(String value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the rehome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRehome() {
        return rehome;
    }

    /**
     * Sets the value of the rehome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRehome(String value) {
        this.rehome = value;
    }

    /**
     * Gets the value of the strictMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrictMatch() {
        return strictMatch;
    }

    /**
     * Sets the value of the strictMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrictMatch(String value) {
        this.strictMatch = value;
    }

}
