//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}SpeedDialIndex"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}SpeedDialNumber"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}SpeedDialLabel"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}SpeedDialBLF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "speedDialIndex",
    "speedDialNumber",
    "speedDialLabel",
    "speedDialBLF"
})
@XmlRootElement(name = "SpeedDial")
public class SpeedDial {

    @XmlElement(name = "SpeedDialIndex", required = true)
    protected String speedDialIndex;
    @XmlElement(name = "SpeedDialNumber", required = true)
    protected String speedDialNumber;
    @XmlElement(name = "SpeedDialLabel", required = true)
    protected String speedDialLabel;
    @XmlElement(name = "SpeedDialBLF", required = true)
    protected String speedDialBLF;

    /**
     * Gets the value of the speedDialIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedDialIndex() {
        return speedDialIndex;
    }

    /**
     * Sets the value of the speedDialIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedDialIndex(String value) {
        this.speedDialIndex = value;
    }

    /**
     * Gets the value of the speedDialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedDialNumber() {
        return speedDialNumber;
    }

    /**
     * Sets the value of the speedDialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedDialNumber(String value) {
        this.speedDialNumber = value;
    }

    /**
     * Gets the value of the speedDialLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedDialLabel() {
        return speedDialLabel;
    }

    /**
     * Sets the value of the speedDialLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedDialLabel(String value) {
        this.speedDialLabel = value;
    }

    /**
     * Gets the value of the speedDialBLF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedDialBLF() {
        return speedDialBLF;
    }

    /**
     * Sets the value of the speedDialBLF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedDialBLF(String value) {
        this.speedDialBLF = value;
    }

}
