//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}primary"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}secondary"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}no-reg"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}no-reg_option"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primary",
    "secondary",
    "noReg",
    "noRegOption"
})
@XmlRootElement(name = "telephony_number")
public class TelephonyNumber {

    @XmlElement(required = true)
    protected String primary;
    @XmlElement(required = true)
    protected String secondary;
    @XmlElement(name = "no-reg", required = true)
    protected String noReg;
    @XmlElement(name = "no-reg_option", required = true)
    protected String noRegOption;

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimary(String value) {
        this.primary = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondary() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondary(String value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the noReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoReg() {
        return noReg;
    }

    /**
     * Sets the value of the noReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoReg(String value) {
        this.noReg = value;
    }

    /**
     * Gets the value of the noRegOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoRegOption() {
        return noRegOption;
    }

    /**
     * Sets the value of the noRegOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoRegOption(String value) {
        this.noRegOption = value;
    }

}
