//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}busy_timeout"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}interdigit_timeout"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}ringing_timeout"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}transfer-recall_timeout"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}night-service-bell_timeout"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "busyTimeout",
    "interdigitTimeout",
    "ringingTimeout",
    "transferRecallTimeout",
    "nightServiceBellTimeout"
})
@XmlRootElement(name = "timeouts")
public class Timeouts {

    @XmlElement(name = "busy_timeout", required = true)
    protected String busyTimeout;
    @XmlElement(name = "interdigit_timeout", required = true)
    protected String interdigitTimeout;
    @XmlElement(name = "ringing_timeout", required = true)
    protected String ringingTimeout;
    @XmlElement(name = "transfer-recall_timeout", required = true)
    protected String transferRecallTimeout;
    @XmlElement(name = "night-service-bell_timeout", required = true)
    protected String nightServiceBellTimeout;

    /**
     * Gets the value of the busyTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusyTimeout() {
        return busyTimeout;
    }

    /**
     * Sets the value of the busyTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusyTimeout(String value) {
        this.busyTimeout = value;
    }

    /**
     * Gets the value of the interdigitTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterdigitTimeout() {
        return interdigitTimeout;
    }

    /**
     * Sets the value of the interdigitTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterdigitTimeout(String value) {
        this.interdigitTimeout = value;
    }

    /**
     * Gets the value of the ringingTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRingingTimeout() {
        return ringingTimeout;
    }

    /**
     * Sets the value of the ringingTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRingingTimeout(String value) {
        this.ringingTimeout = value;
    }

    /**
     * Gets the value of the transferRecallTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferRecallTimeout() {
        return transferRecallTimeout;
    }

    /**
     * Sets the value of the transferRecallTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferRecallTimeout(String value) {
        this.transferRecallTimeout = value;
    }

    /**
     * Gets the value of the nightServiceBellTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNightServiceBellTimeout() {
        return nightServiceBellTimeout;
    }

    /**
     * Sets the value of the nightServiceBellTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNightServiceBellTimeout(String value) {
        this.nightServiceBellTimeout = value;
    }

}
