//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 01:39:09 PM MSK 
//


package com.cisco.cme.custom.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cisco_cme_xml_namespace}url-button"/>
 *         &lt;element ref="{cisco_cme_xml_namespace}url-button_type"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{cisco_cme_xml_namespace}url-button_url"/>
 *           &lt;element ref="{cisco_cme_xml_namespace}url-button_name"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "urlButton",
    "urlButtonType",
    "urlButtonUrl",
    "urlButtonName"
})
@XmlRootElement(name = "url-button_item")
public class UrlButtonItem {

    @XmlElement(name = "url-button", required = true)
    protected String urlButton;
    @XmlElement(name = "url-button_type", required = true)
    protected String urlButtonType;
    @XmlElement(name = "url-button_url")
    protected String urlButtonUrl;
    @XmlElement(name = "url-button_name")
    protected String urlButtonName;

    /**
     * Gets the value of the urlButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlButton() {
        return urlButton;
    }

    /**
     * Sets the value of the urlButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlButton(String value) {
        this.urlButton = value;
    }

    /**
     * Gets the value of the urlButtonType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlButtonType() {
        return urlButtonType;
    }

    /**
     * Sets the value of the urlButtonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlButtonType(String value) {
        this.urlButtonType = value;
    }

    /**
     * Gets the value of the urlButtonUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlButtonUrl() {
        return urlButtonUrl;
    }

    /**
     * Sets the value of the urlButtonUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlButtonUrl(String value) {
        this.urlButtonUrl = value;
    }

    /**
     * Gets the value of the urlButtonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlButtonName() {
        return urlButtonName;
    }

    /**
     * Sets the value of the urlButtonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlButtonName(String value) {
        this.urlButtonName = value;
    }

}
