
package com.cisco.risapi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-29T10:51:42.554+03:00
 * Generated source version: 3.1.6
 * 
 */
public final class RisPortType_RisPort70_Client {

    private static final QName SERVICE_NAME = new QName("http://schemas.cisco.com/ast/soap", "RISService70");

    private RisPortType_RisPort70_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RISService70.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RISService70 ss = new RISService70(wsdlURL, SERVICE_NAME);
        RisPortType port = ss.getRisPort70();  
        
        {
        System.out.println("Invoking selectCmDeviceExt...");
        java.lang.String _selectCmDeviceExt_stateInfo = "";
        com.cisco.risapi.CmSelectionCriteria _selectCmDeviceExt_cmSelectionCriteria = null;
        com.cisco.risapi.SelectCmDeviceReturn _selectCmDeviceExt__return = port.selectCmDeviceExt(_selectCmDeviceExt_stateInfo, _selectCmDeviceExt_cmSelectionCriteria);
        System.out.println("selectCmDeviceExt.result=" + _selectCmDeviceExt__return);


        }
        {
        System.out.println("Invoking selectCmDevice...");
        java.lang.String _selectCmDevice_stateInfo = "";
        com.cisco.risapi.CmSelectionCriteria _selectCmDevice_cmSelectionCriteria = null;
        com.cisco.risapi.SelectCmDeviceReturn _selectCmDevice__return = port.selectCmDevice(_selectCmDevice_stateInfo, _selectCmDevice_cmSelectionCriteria);
        System.out.println("selectCmDevice.result=" + _selectCmDevice__return);


        }
        {
        System.out.println("Invoking selectCtiItem...");
        java.lang.String _selectCtiItem_stateInfo = "";
        com.cisco.risapi.CtiSelectionCriteria _selectCtiItem_ctiSelectionCriteria = null;
        com.cisco.risapi.SelectCtiItemReturn _selectCtiItem__return = port.selectCtiItem(_selectCtiItem_stateInfo, _selectCtiItem_ctiSelectionCriteria);
        System.out.println("selectCtiItem.result=" + _selectCtiItem__return);


        }

        System.exit(0);
    }

}
